### ISSUE TITLE
Uncaught Exception: dlopen(/Applications/Google Play Music Desktop Player.app/Contents/Resources/app/node_modules/mdns/b

### ISSUE THREAD

**Issue by valentijnnieman** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1047]
An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.2.4
**Time:** Sun May 08 2016 15:49:16 GMT 0200 (CEST)

#### Error:
*dlopen(/Applications/Google Play Music Desktop Player.app/Contents/Resources/app/node_modules/mdns/b*
```js
Error: dlopen(/Applications/Google Play Music Desktop Player.app/Contents/Resources/app/node_modules/mdns/build/Release/dns_sd_bindings.node, 1): no suitable image found.  Did find:
/Applications/Google Play Music Desktop Player.app/Contents/Resources/app/node_modules/mdns/build/Release/dns_sd_bindings.node: mach-o, but wrong architecture
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:440:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Applications/Google Play Music Desktop Player.app/Contents/Resources/app/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:413:34)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
What version are you running...

There is no released version with `mdns` as a dependency.

**Comment by valentijnnieman** [comment]
Version 3.2.4 I think. I pulled the repo, ran npm install, npm build and npm run make:darwin. Then I opened the app, it gave an error with a link that took me here. :) Sorry if this is not at all useful.

**Comment by MarshallOfSound** [comment]
@valentijnnieman Yeah, master is unstable, as you can see by the CI builds failing all over the place at the moment.  Current;y it is only stable on Windows.  If you want to use the player, please use the release versions available on our website
