### ISSUE TITLE
Uncaught Exception: ENFILE: file table overflow, open '/Users/blackcathacker/Library/Application Support/Google Play Mus

### ISSUE THREAD

**Issue by blackcathacker** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1074]
An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.2.4
**Time:** Thu May 12 2016 15:45:51 GMT-0700 (PDT)

#### Error:
*ENFILE: file table overflow, open '/Users/blackcathacker/Library/Application Support/Google Play Mus*
```js
Error: ENFILE: file table overflow, open '/Users/blackcathacker/Library/Application Support/Google Play Music Desktop Player/json_store/playback.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:158:20)
    at Object.fs.writeFileSync (fs.js:1234:33)
    at PlaybackAPI._save (/Applications/Google Play Music Desktop Player.app/Contents/Resources/app/build/main/utils/PlaybackAPI.js:101:22)
    at PlaybackAPI._setTime (/Applications/Google Play Music Desktop Player.app/Contents/Resources/app/build/main/utils/PlaybackAPI.js:170:12)
    at EventEmitter.<anonymous> (/Applications/Google Play Music Desktop Player.app/Contents/Resources/app/build/main/utils/PlaybackAPI.js:56:15)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
    at EventEmitter.<anonymous> (/Applications/Google Play Music Desktop Player.app/Contents/Resources/electron.asar/browser/api/web-contents.js:130:25)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
This normally means the OS has too many files open (strange I know).  Not how or why, but yeah, too many files :+1:
