### ISSUE TITLE
Uncaught Exception: Command failed: 4294967295

### ISSUE THREAD

**Issue by mmsibiya** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1134]
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.0
**Time:** Wed Jun 01 2016 07:10:59 GMT 0200 (South Africa Standard Time)

#### Error:
*Command failed: 4294967295*
```js
Error: Command failed: 4294967295
System.AggregateException: One or more errors occurred. ---> System.IO.IOException: The process cannot access the file 'C:\Users\Mandla\AppData\Local\GPMDP_3\app-3.2.4\lib\net45\resources\app\node_modules\ll-keyboard-hook-win\Debug\LLKeyboardHook.exe' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.OpenFile(String path, FileAccess access, SafeFileHandle

**Comment by MarshallOfSound** [comment]
Holy damm....

It looks like you're running an unofficial development version from like.  2 months ago....

If the update notification hasn't popped up in the last 2 months you should probably just download the latest installer again from googleplaymusicdesktopplayer.com
