### ISSUE TITLE
Uncaught Exception: Unknown system error -122: Unknown system error -122, write

### ISSUE THREAD

**Issue by JacopoGobbi** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1142]
An uncaught exception was reported.  
#### Info:
**OS:** linux
**Arch:** x64
**GPMDP Version:** 3.1.0
**Time:** Thu Jun 02 2016 14:29:08 GMT 0100 (BST)

#### Error:
*Unknown system error -122: Unknown system error -122, write*
```js
Error: Unknown system error -122: Unknown system error -122, write
    at Error (native)
    at Object.fs.writeSync (fs.js:706:20)
    at Object.fs.writeFileSync (fs.js:1244:24)
    at PlaybackAPI._save (/usr/share/google-play-music-desktop-player/resources/app/build/main/utils/PlaybackAPI.js:92:22)
    at PlaybackAPI.setTime (/usr/share/google-play-music-desktop-player/resources/app/build/main/utils/PlaybackAPI.js:147:12)
    at EventEmitter.<anonymous> (/usr/share/google-play-music-desktop-player/resources/app/build/main/utils/PlaybackAPI.js:56:15)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.<anonymous> (/usr/share/google-play-music-desktop-player/resources/atom.asar/browser/api/web-contents.js:134:25)
    at emitTwo (events.js:87:13)
```
This issue was created automatically inside the `uncaughtException` handler

1) Pressed multimedia key "play" button on my keyboard.
2) Music started
3) Message about error appeared.

**Comment by MarshallOfSound** [comment]
@jostrander Linux error code?  I don't recognise it

**Comment by jostrander** [comment]
Yeah I think its a standard kernel error message, @JacopoGobbi what kernel version are you running?

**Comment by JacopoGobbi** [comment]
@jostrander I think it was `3.16.0-65-generic`

**Comment by MarshallOfSound** [comment]
After extensive Googling 😆 

I have determined that this error is due to a temporary disk error.  I.e. Nothing to do with this program but an underlying filesystem access thing broke.
