### ISSUE TITLE
Enable Playback API: Uncaught Exception: listen EADDRINUSE 0.0.0.0:5672

### ISSUE THREAD

**Issue by Eugeny** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1178]
Actually I already have a RabbitMQ running on :5672 so maybe choosing a non-standard port is a better idea

An uncaught exception was reported.  
#### Info:
**OS:** linux
**Arch:** x64
**GPMDP Version:** 3.2.4
**Time:** Sat Jun 11 2016 13:56:43 GMT 0200 (CEST)

#### Error:
*listen EADDRINUSE 0.0.0.0:5672*
```js
Error: listen EADDRINUSE 0.0.0.0:5672
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
You can override the port with an environment variable

`GPMDP_API_PORT`

We'll always find port collisions 👍
