### ISSUE TITLE
Uncaught Exception: not opened

### ISSUE THREAD

**Issue by thomassross** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1193]
An uncaught exception was reported.  
#### Info:
**OS:** linux
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Wed Jun 15 2016 22:42:50 GMT-0400 (EDT)

#### Error:
*not opened*
```js
Error: not opened
    at WebSocket.send (/usr/share/google-play-music-desktop-player/resources/app/node_modules/ws/lib/WebSocket.js:218:16)
    at WebSocket.ws.json (/usr/share/google-play-music-desktop-player/resources/app/build/main/features/core/websocketAPI.js:50:12)
    at WebSocket.ws.channel (/usr/share/google-play-music-desktop-player/resources/app/build/main/features/core/websocketAPI.js:53:12)
    at /usr/share/google-play-music-desktop-player/resources/app/build/main/features/core/websocketAPI.js:42:16
    at Array.forEach (native)
    at WebSocketServer.server.broadcast (/usr/share/google-play-music-desktop-player/resources/app/build/main/features/core/websocketAPI.js:41:22)
    at /usr/share/google-play-music-desktop-player/resources/app/build/main/features/core/websocketAPI.js:22:14
    at /usr/share/google-play-music-desktop-player/resources/app/build/main/utils/PlaybackAPI.js:155:9
    at Array.forEach (native)
    at PlaybackAPI._fire (/usr/share/google-play-music-desktop-player/resources/app/build/main/utils/PlaybackAPI.js:154:22)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
Couple of things

1. This issue is fixed in master (possibly even in the latest release)
2. You are on version `3.0.0` the most up to date version if `3.2.4` you should probably update.
