### ISSUE TITLE
Uncaught Exception: dns service error: unknown

### ISSUE THREAD

**Issue by clarjon1** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1254]
An uncaught exception was reported.  
#### Info:
**OS:** linux
**Arch:** x64
**GPMDP Version:** 3.2.4
**Time:** Thu Jun 30 2016 00:23:45 GMT-0400 (EDT)

#### Error:
*dns service error: unknown*
```js
Error: dns service error: unknown
    at Error (native)
    at new Advertisement (/usr/share/google-play-music-desktop-player/resources/app/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/usr/share/google-play-music-desktop-player/resources/app/node_modules/mdns/lib/advertisement.js:64:10)
    at Server.<anonymous> (/usr/share/google-play-music-desktop-player/resources/app/build/main/features/core/websocketAPI.js:56:25)
    at Server.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at Server.emit (events.js:185:7)
    at emitListeningNT (net.js:1279:10)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
It looks like you are running the unstable AUR build on arch

Please use the stable version or install avahi
