### ISSUE TITLE
Uncaught Exception: EBUSY: resource busy or locked, open 'C:\Users\Jamie\AppData\Roaming\Google Play Music Desktop Playe

### ISSUE THREAD

**Issue by livejamie** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1260]
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.2.5
**Time:** Fri Jul 01 2016 16:49:35 GMT-0700 (Pacific Daylight Time)

#### Error:
*EBUSY: resource busy or locked, open 'C:\Users\Jamie\AppData\Roaming\Google Play Music Desktop Playe*
```js
Error: EBUSY: resource busy or locked, open 'C:\Users\Jamie\AppData\Roaming\Google Play Music Desktop Player\json_store\playback.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:158:20)
    at Object.fs.writeFileSync (fs.js:1234:33)
    at PlaybackAPI._save (C:\Users\Jamie\AppData\Local\GPMDP_3\app-3.2.5\resources\app\build\main\utils\PlaybackAPI.js:101:22)
    at PlaybackAPI._setTime (C:\Users\Jamie\AppData\Local\GPMDP_3\app-3.2.5\resources\app\build\main\utils\PlaybackAPI.js:170:12)
    at EventEmitter.<anonymous> (C:\Users\Jamie\AppData\Local\GPMDP_3\app-3.2.5\resources\app\build\main\utils\PlaybackAPI.js:56:15)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
    at EventEmitter.<anonymous> (C:\Users\Jamie\AppData\Local\GPMDP_3\app-3.2.5\resources\electron.asar\browser\api\web-contents.js:130:25)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
Glorious windows...

If this happens really often comment here, but otherwise I think this is a windows one off FS glitch

**Comment by livejamie** [comment]
Getting this error every single day. Is there a way to fix it or disable the notification? Is it bad?
