### ISSUE TITLE
Uncaught Exception: Cannot read property '1' of null

### ISSUE THREAD

**Issue by Zverushko** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1281]
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.3.0
**Time:** Wed Jul 06 2016 15:47:32 GMT 0300 (RTZ 2 (зима))

#### Error:
*Cannot read property '1' of null*
```js
TypeError: Cannot read property '1' of null
    at Request._callback (C:\Users\Zverushko\AppData\Local\GPMDP_3\app-3.3.0\resources\app\build\main\features\core\lyrics\source_lyricsFreak.js:9:1201)
    at Request.self.callback (C:\Users\Zverushko\AppData\Local\GPMDP_3\app-3.3.0\resources\app\node_modules\request\request.js:200:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\Zverushko\AppData\Local\GPMDP_3\app-3.3.0\resources\app\node_modules\request\request.js:1067:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\Zverushko\AppData\Local\GPMDP_3\app-3.3.0\resources\app\node_modules\request\request.js:988:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
That's a new one 😆
