### ISSUE TITLE
Uncaught Exception: EBUSY: resource busy or locked, open 'C:\Users\bruto\AppData\Roaming\Google Play Music Desktop Playe

### ISSUE THREAD

**Issue by Double44** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1291]
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.3.0
**Time:** Fri Jul 08 2016 12:31:39 GMT-0600 (Mountain Daylight Time)

#### Error:
*EBUSY: resource busy or locked, open 'C:\Users\bruto\AppData\Roaming\Google Play Music Desktop Playe*
```js
Error: EBUSY: resource busy or locked, open 'C:\Users\bruto\AppData\Roaming\Google Play Music Desktop Player\json_store\.settings.json'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:158:20)
    at Object.fs.writeFileSync (fs.js:1337:33)
    at t.value (C:\Users\bruto\AppData\Local\GPMDP_3\app-3.3.0\resources\app\build\main\utils\Settings.js:9:2252)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
We should implement some kind of error catching and retry on L70 of Settings.js
