### ISSUE TITLE
Logger is not defined

### ISSUE THREAD

**Issue by lnxmachine** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1319]
**OS:** Windows

**Issue Descriptions:** Javascript error during install, Logger is not defined

**Steps to Reproduce:** I've tried to uninstall/reinstall/reboot serveral times and always get the same errors about the logger is not defined.  Here is one of the error messages:

[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
ReferenceError: Logger is not defined
    at t.value (C:\Users\USERNAME\AppData\Local\GPMDP_3\app-3.3.0\resources\app\build\main\utils\Settings.js:9:1910)
    at new t (C:\Users\USERNAME\AppData\Local\GPMDP_3\app-3.3.0\resources\app\build\main\utils\Settings.js:9:1065)
    at C:\Users\USERNAME\AppData\Local\GPMDP_3\app-3.3.0\resources\app\build\index.js:9:1808
    at Object.<anonymous> (C:\Users\USERNAME\AppData\Local\GPMDP_3\app-3.3.0\resources\app\build\index.js:9:3737)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Object.<anonymous> (C:\Users\USERNAME\AppData\Local\GPMDP_3\app-3.3.0\resources\electron.asar\browser\init.js:180:8)

[OK]

**Comment by MarshallOfSound** [comment]
Please delete your settings file found at `%APPDATA%/Google Play Music Desktop Player/json_store`
