### ISSUE TITLE
Uncaught Exception: UNKNOWN: unknown error, open 'C:\Users\pdima\AppData\Roaming\Google Play Music Desktop Player\json_s

### ISSUE THREAD

**Issue by petrisordima** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1329]
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.3.0
**Time:** Mon Jul 18 2016 14:25:22 GMT 0300 (GTB Daylight Time)

#### Error:
*UNKNOWN: unknown error, open 'C:\Users\pdima\AppData\Roaming\Google Play Music Desktop Player\json_s*
```js
Error: UNKNOWN: unknown error, open 'C:\Users\pdima\AppData\Roaming\Google Play Music Desktop Player\json_store\.settings.json'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:158:20)
    at Object.fs.writeFileSync (fs.js:1337:33)
    at t.value (C:\Users\pdima\AppData\Local\GPMDP_3\app-3.3.0\resources\app\build\main\utils\Settings.js:9:2252)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
`unknown error`

Lol, wonderful error Node....

Thanks...

Not much I do about this one, sorry @petrisordima 😆 Node's error message is horrendous 😆
