### ISSUE TITLE
Install failure on Windows 10 64-bit - "Access to path 'resources' is denied

### ISSUE THREAD

**Issue by scottpletcher** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1346]
**OS:**
Windows 10 Pro 64-bit

**Issue Descriptions:**
Trying to install but get failure message.  Logs seem to indicate the source of the error is here:

2016-07-22 19:14:54> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Access to the path 'resources' is denied.
   at System.IO.DirectoryInfo.MoveTo(String destDirName)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassb4.<>c__DisplayClassb9.<>c__DisplayClassbb.<installPackageToAppDir>b__b2(DirectoryInfo subdir)
   at Squirrel.Utility.<>c__DisplayClass18`1.<>c__DisplayClass1a.<ForEachAsync>b__17()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---

**Steps to Reproduce:**
Download and trying to install on Windows 10 Pro.  Tried normal user and Run as Admin with same results.

**Comment by MarshallOfSound** [comment]
This is an AV issue (If I had to guess you're running Panda anti-virus)

You can override this issue by running the installer as Admin until it gets fixed Upstream
