### ISSUE TITLE
Uncaught Exception: Failed to connect to socket /tmp/dbus-12MTUQ7KVR: Connection refused

### ISSUE THREAD

**Issue by certik** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1663]
It asked me to report it, so here you go. Btw, that's a clever trick to put everything in the URL, so that it's easy to report errors on GitHub! I'll use that too in my programs.

An uncaught exception was reported.  
#### Info:
**OS:** linux
**Arch:** x64
**GPMDP Version:** 3.2.4
**Time:** Wed Sep 21 2016 17:18:35 GMT-0600 (MDT)

#### Error:
*Failed to connect to socket /tmp/dbus-12MTUQ7KVR: Connection refused*
```js
Error: Failed to connect to socket /tmp/dbus-12MTUQ7KVR: Connection refused
    at Error (native)
    at new module.exports (/usr/share/google-play-music-desktop-player/resources/app/node_modules/dbus/lib/bus.js:22:32)
    at DBus.getBus (/usr/share/google-play-music-desktop-player/resources/app/node_modules/dbus/lib/dbus.js:48:12)
    at DBus.registerService (/usr/share/google-play-music-desktop-player/resources/app/node_modules/dbus/lib/dbus.js:106:17)
    at Player.init (/usr/share/google-play-music-desktop-player/resources/app/node_modules/mpris-service/index.js:37:22)
    at new Player (/usr/share/google-play-music-desktop-player/resources/app/node_modules/mpris-service/index.js:30:7)
    at Player (/usr/share/google-play-music-desktop-player/resources/app/node_modules/mpris-service/index.js:15:40)
    at mprisService (/usr/share/google-play-music-desktop-player/resources/app/build/main/features/linux/mprisService.js:19:43)
    at Object.<anonymous> (/usr/share/google-play-music-desktop-player/resources/app/build/main/features/linux/mprisService.js:94:1)
    at Module._compile (module.js:413:34)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
/cc @jostrander 😖 

I really want to close this and say "you broke your perms, welcome to linux" but I'll wait for @jostrander to have a theory 😆

**Comment by jostrander** [comment]
Well first of all, it's 3.2.4, so first guess is to update, however I'm pretty sure we changed nothing with dbus between latest and then. However @MarshallOfSound is pretty spot on, this seems like a permissions issue, or you don't have DBus available? What flavor / distro of linux are you running?

**Comment by certik** [comment]
I am running Ubuntu 16.04. I updated to 3.6.0-1. Now in the terminal, it says:
```
(google-play-music-desktop-player:27336): GLib-GIO-CRITICAL **: g_dbus_connection_register_object: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(google-play-music-desktop-player:27336): GLib-GIO-CRITICAL **: g_dbus_connection_register_object: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(google-play-music-desktop-player:27336): GLib-GIO-CRITICAL **: g_dbus_connection_get_unique_name: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(google-play-music-desktop-player:27336): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Failed to connect to socket /tmp/dbus-12MTUQ7KVR: Connection refused
error: Failed to load bonjour with error: {}
Bonjour is required to use Chromecast Support or to enable ZeroConf for the PlaybackAPI
On linux you need to install "avahi"
error: Uncaught Exception. Error: Failed to connect to socket /tmp/dbus-12MTUQ7KVR: Connection refused
    at Error (native)
    at new module.exports (/usr/share/google-play-music-desktop-player/resources/app/node_modules/dbus/lib/bus.js:22:32)
    at DBus.getBus (/usr/share/google-play-music-desktop-player/resources/app/node_modules/dbus/lib/dbus.js:48:12)
    at DBus.registerService (/usr/share/google-play-music-desktop-player/resources/app/node_modules/dbus/lib/dbus.js:106:17)
    at Player.init (/usr/share/google-play-music-desktop-player/resources/app/node_modules/mpris-service/index.js:37:22)
    at new Player (/usr/share/google-play-music-desktop-player/resources/app/node_modules/mpris-service/index.js:30:7)
    at Player (/usr/share/google-play-music-desktop-player/resources/app/node_modules/mpris-service/index.js:15:40)
    at mprisService (/usr/share/google-play-music-desktop-player/resources/app/build/main/features/linux/mprisService.js:9:181)
    at Object.<anonymous> (/usr/share/google-play-music-desktop-player/resources/app/build/main/features/linux/mprisService.js:9:1634)
    at Module._compile (module.js:541:32)

(google-play-music-desktop-player:27336): libappindicator-WARNING **: Unable to get the session bus: Could not connect: Connection refused

(google-play-music-desktop-player:27336): LIBDBUSMENU-GLIB-WARNING **: Unable to get session bus: Could not connect: Connection refused
```
Why is it trying to connect to `/tmp/dbus-12MTUQ7KVR`? I don't have that file in /tmp. My permissions there are working otherwise.

**Comment by jostrander** [comment]
Try running `dbus-launch` and then starting GPMDP

**Comment by certik** [comment]
@jostrander I restarted the computer. Now it works...
```
error: Failed to load bonjour with error: {}
Bonjour is required to use Chromecast Support or to enable ZeroConf for the PlaybackAPI
On linux you need to install "avahi"
error: ################### !! Update server down !! ##################
Failed to encode dictionary
Failed to encode reply value
```
So dbus must have been broken or something. 

Note that there is no `dbus*` file in tmy /tmp:
```
$ ll /tmp/dbus*
ls: cannot access '/tmp/dbus*': No such file or directory
```
