### ISSUE TITLE
Black Window in 4.0.1

### ISSUE THREAD

**Issue by Cistoran** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1783]
**OS:** Windows 10

**Issue Descriptions:** Program launches with a black screen.

I've had this issue since 3.2.5ish, I was optimistic seeing the changes in 4.0.1 but still have the issue unfortunately.

**Steps to Reproduce:** Launch the program and wait 10-15 seconds.

Here is a log file from running it with --dev. I tried to get the DEBUG_INFO but it says it can't find the path (possibly because it's now inside app-4.0.1?)

```
info: Application started.
Unexpected result while probing for avahi: { Error: dns service error: unknown error code
    at Error (native)
    at supportsInterfaceIndexLocalOnly (C:\Users\i55171\AppData\Local\GPMDP_3\app-4.0.1\resources\app.asar\node_modules\mdns\lib\avahi.js:17:12)
    at Object.<anonymous> (C:\Users\i55171\AppData\Local\GPMDP_3\app-4.0.1\resources\app.asar\node_modules\mdns\lib\avahi.js:32:20)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\i55171\AppData\Local\GPMDP_3\app-4.0.1\resources\app.asar\node_modules\mdns\lib\mdns.js:31:19)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\i55171\AppData\Local\GPMDP_3\app-4.0.1\resources\app.asar\build\main\features\core\websocketAPI.js:9:580)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\i55171\AppData\Local\GPMDP_3\app-4.0.1\resources\app.asar\build\main\features\core\index.js:9:235)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\i55171\AppData\Local\GPMDP_3\app-4.0.1\resources\app.asar\build\main\features\index.js:9:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at App.<anonymous> (C:\Users\i55171\AppData\Local\GPMDP_3\app-4.0.1\resources\app.asar\build\index.js:9:3538)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7) errorCode: -65563 }
error: Failed to load bonjour with error: {}
Bonjour is required to use Chromecast Support or to enable ZeroConf for the PlaybackAPI
On windows you need to install Bonjour Print Services
[8776:1017/085805:INFO:CONSOLE(75)] "Download the React DevTools and use an HTTP server (instead of a file: URL) for a better development experience: https://fb.me/react-devtools", source: C:\Users\i55171\AppData\Local\GPMDP_3\app-4.0.1\resources\app.asar\node_modules\react\lib\ReactDOM.js (75)
[8776:1017/085806:INFO:CONSOLE(294)] "::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source: C:\Users\i55171\AppData\Local\GPMDP_3\app-4.0.1\resources\electron.asar\renderer\web-view\web-view.js (294)
debug: Renderer process logger initialized.
[11760:1017/085811:WARNING:webmediaplayer_impl.cc(341)] Using MultibufferDataSource
[11760:1017/085811:ERROR:ffmpeg_demuxer.cc(1510)] media::FFmpegDemuxer::OnReadFrameDone result=-541478725 IsMaxMemoryUsageReached=0
[11760:1017/085822:ERROR:atom_bindings.cc(78)] Fatal error in V8: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
Backtrace:
        (No symbol) [0x003F1FC9]
        v8::FunctionTemplate::RemovePrototype [0x6AAB6154+180]
        v8::SharedArrayBuffer::Externalize [0x6AAA6BD4+740]
        v8::String::WriteUtf8 [0x6AACD2E9+63977]
        v8::Locker::IsLocked [0x6A93B9A9+329225]
        v8::Locker::IsLocked [0x6A942447+356519]
        v8::Locker::IsLocked [0x6A94194E+353710]
        v8::experimental::FastAccessorBuilder::SetLabel [0x6AE74991+598673]
        (No symbol) [0x1460B9A6]
        (No symbol) [0x1462A4A5]
        (No symbol) [0x37446F3D]
        (No symbol) [0x1460B5D6]
        (No symbol) [0x37420BE4]
        (No symbol) [0x374205F0]
        (No symbol) [0x37420868]
        (No symbol) [0x374202A7]
        (No symbol) [0x14C8DF00]
        (No symbol) [0x14C8DB99]
        (No symbol) [0x1460B5D6]
        (No symbol) [0x37440E91]
        (No symbol) [0x146394DE]
        (No symbol) [0x146245C3]
        v8::String::WriteUtf8 [0x6AAD9693+114067]
        v8::String::WriteUtf8 [0x6AAD8EE5+112101]
        v8::Function::Call [0x6AAA02D4+468]
        v8::Function::Call [0x6AAA00E4+52]
        v8::RetainedObjectInfo::GetSizeInBytes [0x6A6740C5+639]
        v8::Value::IsUndefined [0x6A676544+174]
        v8::String::ExternalStringResourceBase::IsCompressible [0x6A6B11FA+33153]
        uv_tcp_simultaneous_accepts [0x6AC73C89+2932]
        uv_loop_init [0x6AC60D10+1301]
        uv_run [0x6AC60DF9+82]
        (No symbol) [0x003F3EF5]
        (No symbol) [0x003F3DF7]
        GetHandleVerifier [0x005B3707+247751]
        icu_56::Calendar::weekNumber [0x01BCE597+3444039]
        icu_56::Calendar::weekNumber [0x01BCDDB3+3442019]
        icu_56::Calendar::weekNumber [0x01BCE915+3444933]
        GetHandleVerifier [0x005B3707+247751]
        (No symbol) [0x0056C6DB]
        (No symbol) [0x0056BAF5]
        GetHandleVerifier [0x005B5AC0+256896]
        (No symbol) [0x0056C3D1]
        (No symbol) [0x0056C3AD]
        icu_56::TimeZone::setID [0x00C6B3B9+2124841]
        icu_56::BreakIterator::isBufferClone [0x006C0C40+414720]
        icu_56::BreakIterator::isBufferClone [0x006C0AE5+414373]
        icu_56::BreakIterator::isBufferClone [0x006BDC03+402371]
        (No symbol) [0x003B23F2]
        icu_56::Transliterator::setID [0x029B7622+262034]
        BaseThreadInitThunk [0x747C3744+36]
        RtlSetCurrentTransaction [0x77689E54+212]
        RtlSetCurrentTransaction [0x77689E1F+159]
error:  Error: ENOENT: no such file or directory, stat 'C:\Users\i55171\AppData\Local\GPMDP_3\SquirrelSetup.log'
    at Error (native)
error:  Error: ENOENT: no such file or directory, stat 'C:\Users\i55171\AppData\Local\GPMDP_3\SquirrelSetup.log'
    at Error (native)
error:  Error: ENOENT: no such file or directory, stat 'C:\Users\i55171\AppData\Local\GPMDP_3\SquirrelSetup.log'
    at Error (native)

```

**Comment by jostrander** [comment]
```[11760:1017/085822:ERROR:atom_bindings.cc(78)] Fatal error in V8: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory``` 

Some kind of memory leak or something with electron?

**Comment by MarshallOfSound** [comment]
Argh, I thought this was fixed in `4.0.1`.....  It fixed it for everyone else 😢 

However this

```bash
error:  Error: ENOENT: no such file or directory, stat 'C:\Users\i55171\AppData\Local\GPMDP_3\SquirrelSetup.log'
    at Error (native)
```

Appears to imply something went miserably wrong with your install if that file doesn't exist.  I would suggest uninstalling.  Disabling all antivirus programs and reinstalling `4.0.1`.

**Comment by Cistoran** [comment]
I upgraded from 3.2.4 previously so that was probably the issue on that part. I uninstalled and reinstalled 4.0.1 completely, here's the stack trace from that, and the DEBUG_INFO is attached.

```
info: Application started.
Unexpected result while probing for avahi: { Error: dns service error: unknown error code
    at Error (native)
    at supportsInterfaceIndexLocalOnly (C:\Users\i55171\AppData\Local\GPMDP_3\app-4.0.1\resources\app.asar\node_modules\mdns\lib\avahi.js:17:12)
    at Object.<anonymous> (C:\Users\i55171\AppData\Local\GPMDP_3\app-4.0.1\resources\app.asar\node_modules\mdns\lib\avahi.js:32:20)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\i55171\AppData\Local\GPMDP_3\app-4.0.1\resources\app.asar\node_modules\mdns\lib\mdns.js:31:19)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\i55171\AppData\Local\GPMDP_3\app-4.0.1\resources\app.asar\build\main\features\core\websocketAPI.js:9:580)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\i55171\AppData\Local\GPMDP_3\app-4.0.1\resources\app.asar\build\main\features\core\index.js:9:235)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\i55171\AppData\Local\GPMDP_3\app-4.0.1\resources\app.asar\build\main\features\index.js:9:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at App.<anonymous> (C:\Users\i55171\AppData\Local\GPMDP_3\app-4.0.1\resources\app.asar\build\index.js:9:3538)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7) errorCode: -65563 }
error: Failed to load bonjour with error: {}
Bonjour is required to use Chromecast Support or to enable ZeroConf for the PlaybackAPI
On windows you need to install Bonjour Print Services
[2228:1017/162707:INFO:CONSOLE(75)] "Download the React DevTools and use an HTTP server (instead of a file: URL) for a better development experience: https://fb.me/react-devtools", source: C:\Users\i55171\AppData\Local\GPMDP_3\app-4.0.1\resources\app.asar\node_modules\react\lib\ReactDOM.js (75)
[2228:1017/162708:INFO:CONSOLE(294)] "::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source: C:\Users\i55171\AppData\Local\GPMDP_3\app-4.0.1\resources\electron.asar\renderer\web-view\web-view.js (294)
debug: Renderer process logger initialized.
[11364:1017/162801:ERROR:atom_bindings.cc(78)] Fatal error in V8: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
Backtrace:
        (No symbol) [0x00AE1FC9]
        v8::FunctionTemplate::RemovePrototype [0x69366154+180]
        v8::SharedArrayBuffer::Externalize [0x69356BD4+740]
        v8::String::WriteUtf8 [0x6937D2E9+63977]
        v8::Locker::IsLocked [0x691EB9A9+329225]
        v8::Locker::IsLocked [0x691F2447+356519]
        v8::Locker::IsLocked [0x691F194E+353710]
        v8::experimental::FastAccessorBuilder::SetLabel [0x69724991+598673]
        (No symbol) [0x38E0B9A6]
        (No symbol) [0x38E2A4A5]
        (No symbol) [0x12366C3B]
        (No symbol) [0x38E0B5D6]
        (No symbol) [0x1235B644]
        (No symbol) [0x1235AA10]
        (No symbol) [0x1235AC88]
        (No symbol) [0x1235A647]
        (No symbol) [0x12314C20]
        (No symbol) [0x123148B9]
        (No symbol) [0x38E0B5D6]
        (No symbol) [0x1235A469]
        (No symbol) [0x38E394DE]
        (No symbol) [0x38E245C3]
        v8::String::WriteUtf8 [0x69389693+114067]
        v8::String::WriteUtf8 [0x69388EE5+112101]
        v8::Function::Call [0x693502D4+468]
        v8::Function::Call [0x693500E4+52]
        v8::RetainedObjectInfo::GetSizeInBytes [0x68F240C5+639]
        v8::Value::IsUndefined [0x68F26544+174]
        v8::String::ExternalStringResourceBase::IsCompressible [0x68F611FA+33153]
        uv_tcp_simultaneous_accepts [0x69523C89+2932]
        uv_loop_init [0x69510D10+1301]
        uv_run [0x69510DF9+82]
        (No symbol) [0x00AE3EF5]
        (No symbol) [0x00AE3DF7]
        GetHandleVerifier [0x00CA3707+247751]
        icu_56::Calendar::weekNumber [0x022BE597+3444039]
        icu_56::Calendar::weekNumber [0x022BDDB3+3442019]
        icu_56::Calendar::weekNumber [0x022BE915+3444933]
        GetHandleVerifier [0x00CA3707+247751]
        (No symbol) [0x00C5C6DB]
        (No symbol) [0x00C5BAF5]
        GetHandleVerifier [0x00CA5AC0+256896]
        (No symbol) [0x00C5C3D1]
        (No symbol) [0x00C5C3AD]
        icu_56::TimeZone::setID [0x0135B3B9+2124841]
        icu_56::BreakIterator::isBufferClone [0x00DB0C40+414720]
        icu_56::BreakIterator::isBufferClone [0x00DB0AE5+414373]
        icu_56::BreakIterator::isBufferClone [0x00DADC03+402371]
        (No symbol) [0x00AA23F2]
        icu_56::Transliterator::setID [0x030A7622+262034]
        BaseThreadInitThunk [0x747C3744+36]
        RtlSetCurrentTransaction [0x77689E54+212]
        RtlSetCurrentTransaction [0x77689E1F+159]
```

**Comment by Cistoran** [comment]
@MarshallOfSound I tried to change the label to unmark it Awaiting Response but I think only you can do that :)

**Comment by MarshallOfSound** [comment]
@Cistoran Sorry man, I've been busy recently 👍 

I took a look into this crash and apparently it should be fixed by a V8 bump (supposedly it was a known issue that has been fixed).  The next V8 bump will come with Chromium 54 so just hold out for that 👍

**Comment by y-gagar1n** [comment]
Is there any progress on this issue?
I am having the same error and stacktrace on 4.0.3 and Windows 7.
Don't want to create a duplicate, so I'm asking here.
