### ISSUE TITLE
Invalid Sentry DSN: undefined

### ISSUE THREAD

**Issue by Flat** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1836]
**OS:** Linux 4.8.4

**Issue Descriptions:** On launch the following error is shown and the desktop settings tab doesn't function.
```
Uncaught Exception:
Error: Invalid Sentry DSN: undefined
    at Object.parseDSN (/usr/share/gpmdp/resources/app.asar/node_modules/raven/lib/utils.js:53:11)
    at new Client (/usr/share/gpmdp/resources/app.asar/node_modules/raven/lib/client.js:40:20)
    at Object.<anonymous> (/usr/share/gpmdp/resources/app.asar/build/main/features/core/errorHandler.js:32:16)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/gpmdp/resources/app.asar/build/main/features/core/index.js:11:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/gpmdp/resources/app.asar/build/main/features/index.js:11:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at App.<anonymous> (/usr/share/gpmdp/resources/app.asar/build/index.js:184:5)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)

```

**Steps to Reproduce:** 
1. Build and install from git master
2. launch

**Comment by jostrander** [comment]
The DSN isn't filled in obviously so the error just needs to be caught when its not defined before build. @MarshallOfSound

**Comment by Flat** [comment]
Error still shows in latest commit.

**Comment by MarshallOfSound** [comment]
@Flat Did you run `npm run build` after you pulled from github?

**Comment by Flat** [comment]
@MarshallOfSound Yes.

**Comment by MarshallOfSound** [comment]
@Flat What are you even doing, it shouldn't be going into that block unless you are running a packaged distributable version?

**Comment by Flat** [comment]
```
git pull
npm update
npm run build
npm run package:linux:64
```
https://aur.archlinux.org/packages/gpmdp-git/

So yes, a packaged version.

**Comment by RyuzakiKK** [comment]
Same error here, and I used gpmdp-git too.

**Comment by MarshallOfSound** [comment]
@Flat @RyuzakiKK Please try latest master

**Comment by Flat** [comment]
@MarshallOfSound no errors and desktop settings work. Thanks.

**Comment by RyuzakiKK** [comment]
@MarshallOfSound I confirm that now it works.
