### ISSUE TITLE
v2.1.1 won't start

### ISSUE THREAD

**Issue by sean-clayton** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#186]
OS: Windows 10 Pro (doubt the pro matters)
Version: 2.1.1

Here are some event viewer logs--looks like XML stuff, maybe?

```
Application: Google Play Music.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Xml.XmlException
   at System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32 ByRef, Int32 ByRef, Int32 ByRef)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Skip()
   at System.Configuration.XmlUtil.StrictSkipToNextElement(System.Configuration.ExceptionAction)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSections(System.Configuration.XmlUtil)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors)
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)
   at System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(System.Configuration.Internal.InternalConfigEventArgs)
   at System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(System.String, System.Configuration.BaseConfigurationRecord)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(System.String, Boolean, Boolean, Boolean, Boolean, System.Object ByRef, System.Object ByRef)
   at System.Configuration.BaseConfigurationRecord.GetSection(System.String)
   at System.Configuration.ClientSettingsStore.ReadSettings(System.String, Boolean)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(System.Configuration.SettingsContext, System.Configuration.SettingsPropertyCollection)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(System.Configuration.SettingsProvider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(System.String)
   at System.Configuration.SettingsBase.get_Item(System.String)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(System.String)
   at System.Configuration.ApplicationSettingsBase.get_Item(System.String)
   at Google_Play_Music.Properties.Settings.get_LastFMUsername()
   at Google_Play_Music.LastFM..ctor()
   at Google_Play_Music.Program.Main()
```

```
Faulting application name: Google Play Music.exe, version: 1.0.0.0, time stamp: 0x56af9264
Faulting module name: KERNELBASE.dll, version: 10.0.10586.103, time stamp: 0x56a8489c
Exception code: 0xe0434352
Fault offset: 0x0000000000071f08
Faulting process id: 0x2884
Faulting application start time: 0x01d16a04e3b0705f
Faulting application path: C:\Program Files\GPMDP\Google Play Music.exe
Faulting module path: C:\WINDOWS\system32\KERNELBASE.dll
Report Id: 3bb761fd-a744-4fda-9d4c-08e91912d849
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Fault bucket 129018370081, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Google Play Music.exe
P2: 1.0.0.0
P3: 56af9264
P4: System.Xml
P5: 4.6.1064.2
P6: 565f9c84
P7: b79
P8: 27
P9: IOIBMURHYNRXKW0ZXKYRVFN0BOYYUFOW
P10: 

Attached files:
C:\Users\live\AppData\Local\Temp\WERA29A.tmp.WERInternalMetadata.xml

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Google Play Musi_4564c88b43d8c1972af2ad52fcdedbc9dc60f3_5b51ba87_290fac9c

Analysis symbol: 
Rechecking for solution: 0
Report Id: 3bb761fd-a744-4fda-9d4c-08e91912d849
Report Status: 0
Hashed bucket: d83cfc61454bcfd1f82706ea0e77c191
```

**Comment by MarshallOfSound** [comment]
Looks like you've managed to corrupt the settings schema file.

Please delete everything in `C:\Program Files\GPMDP`, then uninstall.  Then reinstall.

Let me know how it goes :)

**Comment by sean-clayton** [comment]
@MarshallOfSound Did exactly that, and I got the same errors :cry:

**Comment by MarshallOfSound** [comment]
OK, can you do the whole "delete everything" again.  But this time also remove all folders from

`%LOCALAPPDATA%` and `%APPDATA%` that are ANYTHING to do with **GPMDP** or **Google Play Music**

**Comment by wwwertdf** [comment]
Excellent, Deleting Google_Play_Music from Local AppData and GPMDP from
Program Files and Roaming Worked. Perhaps consider removing

**Comment by MarshallOfSound** [comment]
They are required folders, but possibly something became corrupt during the upgrade process

**Comment by wwwertdf** [comment]
Fair enough. Gotta say I love the software man, picked it up a couple weeks
ago, haven't looked back. I needed something coming from my Mac back to PC
(I used Radiant on the Mac)

**Comment by MarshallOfSound** [comment]
So I can close this issue now?  It's all sorted?

Also BTW Mac support is coming in `3.0.0` if you still use your mac :+1:

**Comment by wwwertdf** [comment]
Excellent. Excited to hear, I'd say mark it as resolved.

**Comment by sean-clayton** [comment]
I just got home and did the steps: Worked for me! Thank you for the help!
