### ISSUE TITLE
Black screen on 4.0.3 Windows 7 SP1

### ISSUE THREAD

**Issue by y-gagar1n** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1943]
**OS:**

Windows 7 SP1

**Issue Descriptions:**

Version 4.0.3

The app works normally for about 10-15 minutes and then music stops playing and I see just black screen.

![black_screen](https://cloud.githubusercontent.com/assets/2000558/20476235/f8c5e146-afe0-11e6-8a22-5b36869d6759.png)

I have followed the instructions [here](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1783) and my log is given below.

I've seen the same stacktrace in [this issue](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1783) but unfortunately I don't know what "V8 bump" means and it isn't clear for me what should I do to fix this. Should I update something? 

```
info: Application started.
Unexpected result while probing for avahi: { Error: dns service error: unknown error code
    at Error (native)
    at supportsInterfaceIndexLocalOnly (C:\Users\XXXXX\AppData\Local\GPMDP_3\app-4.0.3\resources\app.asar\node_modules\mdns\lib\avahi.js:17:12)
    at Object.<anonymous> (C:\Users\XXXXX\AppData\Local\GPMDP_3\app-4.0.3\resources\app.asar\node_modules\mdns\lib\avahi.js:32:20)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\XXXXX\AppData\Local\GPMDP_3\app-4.0.3\resources\app.asar\node_modules\mdns\lib\mdns.js:31:19)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\XXXXX\AppData\Local\GPMDP_3\app-4.0.3\resources\app.asar\build\main\features\core\websocketAPI.js:48:10)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\XXXXX\AppData\Local\GPMDP_3\app-4.0.3\resources\app.asar\build\main\features\core\index.js:29:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\XXXXX\AppData\Local\GPMDP_3\app-4.0.3\resources\app.asar\build\main\features\index.js:11:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at App.<anonymous> (C:\Users\XXXXX\AppData\Local\GPMDP_3\app-4.0.3\resources\app.asar\build\index.js:184:5)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7) errorCode: -65563 }
error: Failed to load bonjour with error: {}
Bonjour is required to use Chromecast Support or to enable ZeroConf for the PlaybackAPI
On windows you need to install Bonjour Print Services
[8096:1121/110100:INFO:CONSOLE(75)] "Download the React DevTools and use an HTTP server (instead of a file: URL) for a better development experience: https://fb.me/react-devtools", source: C:\Users\XXXXX\AppData\Local\GPMDP_3\app-4.0.3\resources\app.asar\node_modules\react\lib\ReactDOM.js (75)
[8096:1121/110102:INFO:CONSOLE(294)] "::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source: C:\Users\XXXXX\AppData\Local\GPMDP_3\app-4.0.3\resources\electron.asar\renderer\web-view\web-view.js (294)
debug: Renderer process logger initialized.
[984:1121/110108:WARNING:webmediaplayer_impl.cc(341)] Using MultibufferDataSource
[984:1121/110108:ERROR:ffmpeg_demuxer.cc(1510)] media::FFmpegDemuxer::OnReadFrameDone result=-541478725 IsMaxMemoryUsageReached=0
error: ################### !! Update server down !! ##################
verbose: Lyrics parsing failed
error: ################### !! Update server down !! ##################
verbose: Lyrics parsing failed
error: ################### !! Update server down !! ##################
error: ################### !! Update server down !! ##################
verbose: Lyrics parsing failed
error: ################### !! Update server down !! ##################
error: ################### !! Update server down !! ##################
verbose: Lyrics parsing failed
error: ################### !! Update server down !! ##################
error: ################### !! Update server down !! ##################
verbose: Lyrics parsing failed
error: ################### !! Update server down !! ##################
error: ################### !! Update server down !! ##################
verbose: Lyrics parsing failed
error: ################### !! Update server down !! ##################
error: ################### !! Update server down !! ##################
verbose: Lyrics parsing failed
error: ################### !! Update server down !! ##################
verbose: Lyrics parsing failed
error: ################### !! Update server down !! ##################
verbose: Lyrics parsing failed
error: ################### !! Update server down !! ##################
error: ################### !! Update server down !! ##################
verbose: Lyrics parsing failed
error: ################### !! Update server down !! ##################
[984:1121/114056:ERROR:atom_bindings.cc(78)] Fatal error in V8: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
Backtrace:
        (No symbol) [0x0132EC95]
        v8::FunctionTemplate::RemovePrototype [0x0FC16154+180]
        v8::SharedArrayBuffer::Externalize [0x0FC06BD4+740]
        v8::String::WriteUtf8 [0x0FC2D2E9+63977]
        v8::Locker::IsLocked [0x0FA9B9A9+329225]
        v8::Locker::IsLocked [0x0FAA2447+356519]
        v8::Locker::IsLocked [0x0FAA194E+353710]
        v8::experimental::FastAccessorBuilder::SetLabel [0x0FFD4991+598673]
        (No symbol) [0x0DF0B9A6]
        (No symbol) [0x0DF2A4A5]
        (No symbol) [0x20D17562]
        (No symbol) [0x20D20149]
        (No symbol) [0x20D1FE85]
        (No symbol) [0x1E61A898]
        (No symbol) [0x0DF0B5D6]
        (No symbol) [0x5CBD0545]
        (No symbol) [0x20D307B0]
        (No symbol) [0x0DF0B5D6]
        (No symbol) [0x1E618BE2]
        (No symbol) [0x1E618787]
        (No symbol) [0x1E6DC440]
        (No symbol) [0x1E6DC0D9]
        v8::String::WriteUtf8 [0x0FC39693+114067]
        v8::String::WriteUtf8 [0x0FC38EE5+112101]
        v8::Function::Call [0x0FC002D4+468]
        v8::Function::Call [0x0FC000E4+52]
        v8::RetainedObjectInfo::GetSizeInBytes [0x0F7D40C5+639]
        v8::Value::IsUndefined [0x0F7D6544+174]
        v8::String::ExternalStringResourceBase::IsCompressible [0x0F8111FA+33153]
        uv_tcp_simultaneous_accepts [0x0FDD3C89+2932]
        uv_loop_init [0x0FDC0D10+1301]
        uv_run [0x0FDC0DF9+82]
        (No symbol) [0x01354C9A]
        (No symbol) [0x01354B9C]
        GetHandleVerifier [0x0151EA67+245303]
        icu_56::Calendar::weekNumber [0x02B392F7+3440871]
        icu_56::Calendar::weekNumber [0x02B38B13+3438851]
        icu_56::Calendar::weekNumber [0x02B39675+3441765]
        GetHandleVerifier [0x0151EA67+245303]
        (No symbol) [0x014D7A4B]
        (No symbol) [0x014D6E65]
        GetHandleVerifier [0x01520E20+254448]
        (No symbol) [0x014D7741]
        (No symbol) [0x014D771D]
        icu_56::TimeZone::setID [0x01BD62B9+2124729]
        icu_56::BreakIterator::isBufferClone [0x0162C060+414736]
        icu_56::BreakIterator::isBufferClone [0x0162BF05+414389]
        icu_56::BreakIterator::isBufferClone [0x01629033+402403]
        (No symbol) [0x01312572]
        icu_56::Transliterator::setID [0x03922363+261987]
        BaseThreadInitThunk [0x770A33AA+18]
        RtlInitializeExceptionChain [0x77D39F72+99]
        RtlInitializeExceptionChain [0x77D39F45+54]
```

**Steps to Reproduce:**

Run the app, play music, wait for 10-15 minutes.

**Comment by MarshallOfSound** [comment]
This is a V8 bug that will be fixed upstream.  Just gonna have to wait out the Chromium 54 update 👍
