### ISSUE TITLE
Uncaught Exception: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS

### ISSUE THREAD

**Issue by alerque** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2049]
No particular action seems to have triggered this. I've had GPMDP open for several days and left it for the weekend. Arriving back after the weekend the warning was waiting for me, although it seems to still play music fine.

----

An uncaught exception was reported.  
#### Info:
**OS:** linux
**Arch:** x64
**GPMDP Version:** 3.2.4
**Time:** Mon Dec 26 2016 11:50:52 GMT 0300 ( 03)

#### Error:
*Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS*
```js
Error: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
    at Error (native)
    at new module.exports (/usr/share/google-play-music-desktop-player/resources/app/node_modules/dbus/lib/bus.js:22:32)
    at DBus.getBus (/usr/share/google-play-music-desktop-player/resources/app/node_modules/dbus/lib/dbus.js:48:12)
    at DBus.registerService (/usr/share/google-play-music-desktop-player/resources/app/node_modules/dbus/lib/dbus.js:106:17)
    at Player.init (/usr/share/google-play-music-desktop-player/resources/app/node_modules/mpris-service/index.js:37:22)
    at new Player (/usr/share/google-play-music-desktop-player/resources/app/node_modules/mpris-service/index.js:30:7)
    at Player (/usr/share/google-play-music-desktop-player/resources/app/node_modules/mpris-service/index.js:15:40)
    at mprisService (/usr/share/google-play-music-desktop-player/resources/app/build/main/features/linux/mprisService.js:19:43)
    at Object.<anonymous> (/usr/share/google-play-music-desktop-player/resources/app/build/main/features/linux/mprisService.js:94:1)
    at Module._compile (module.js:541:32)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
> GPMDP Version: 3.2.4

I thought I'd never see this bot ever again 😆  That version is very old, you should probably update to `v4` 👍

**Comment by naveenmittal04** [comment]
i have similar error and i am no using GPMDP . any solution?
