### ISSUE TITLE
Uncaught Exception: ENOSPC: no space left on device, write

### ISSUE THREAD

**Issue by balthasar** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2095]
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.2.4
**Time:** Wed Jan 11 2017 14:09:38 GMT 0200 (South Africa Standard Time)

#### Error:
*ENOSPC: no space left on device, write*
```js
Error: ENOSPC: no space left on device, write
    at Error (native)
    at Object.fs.writeSync (fs.js:706:20)
    at Object.fs.writeFileSync (fs.js:1244:24)
    at PlaybackAPI._save (C:\Users\richardh\AppData\Local\GPMDP_3\app-3.2.4\resources\app\build\main\utils\PlaybackAPI.js:101:22)
    at PlaybackAPI._setTime (C:\Users\richardh\AppData\Local\GPMDP_3\app-3.2.4\resources\app\build\main\utils\PlaybackAPI.js:170:12)
    at EventEmitter.<anonymous> (C:\Users\richardh\AppData\Local\GPMDP_3\app-3.2.4\resources\app\build\main\utils\PlaybackAPI.js:56:15)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
    at EventEmitter.<anonymous> (C:\Users\richardh\AppData\Local\GPMDP_3\app-3.2.4\resources\electron.asar\browser\api\web-contents.js:130:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
I mean, it's good to see the unicorn still works.  But you are on super old version of GPMDP and this error is obviously an issue with your device.

Update to latest and free up some space on your drive.
