### ISSUE TITLE
electron fails on npm start

### ISSUE THREAD

**Issue by parkerlreed** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#210]
Arch x86_64

````
[parker@x3720 Google-Play-Music-Desktop-Player-UNOFFICIAL-]$ npm start

> google-play-music-desktop-player@3.0.0 start /home/parker/build/Google-Play-Music-Desktop-Player-UNOFFICIAL-
> electron .

Error opening app
The app provided is not a valid Electron app, please read the docs on how to write one:
https://github.com/atom/electron/tree/v0.36.7/docs

Error: Cannot find module '/home/parker/build/Google-Play-Music-Desktop-Player-UNOFFICIAL-'

npm ERR! Linux 4.4.3-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v5.7.1
npm ERR! npm  v3.8.0
npm ERR! code ELIFECYCLE
npm ERR! google-play-music-desktop-player@3.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the google-play-music-desktop-player@3.0.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the google-play-music-desktop-player package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs google-play-music-desktop-player
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls google-play-music-desktop-player
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/parker/build/Google-Play-Music-Desktop-Player-UNOFFICIAL-/npm-debug.log
````

````
[parker@x3720 Google-Play-Music-Desktop-Player-UNOFFICIAL-]$ cat npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@3.8.0
3 info using node@v5.7.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle google-play-music-desktop-player@3.0.0~prestart: google-play-music-desktop-player@3.0.0
6 silly lifecycle google-play-music-desktop-player@3.0.0~prestart: no script for prestart, continuing
7 info lifecycle google-play-music-desktop-player@3.0.0~start: google-play-music-desktop-player@3.0.0
8 verbose lifecycle google-play-music-desktop-player@3.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle google-play-music-desktop-player@3.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/parker/build/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/.bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
10 verbose lifecycle google-play-music-desktop-player@3.0.0~start: CWD: /home/parker/build/Google-Play-Music-Desktop-Player-UNOFFICIAL-
11 silly lifecycle google-play-music-desktop-player@3.0.0~start: Args: [ '-c', 'electron .' ]
12 silly lifecycle google-play-music-desktop-player@3.0.0~start: Returned: code: 1  signal: null
13 info lifecycle google-play-music-desktop-player@3.0.0~start: Failed to exec start script
14 verbose stack Error: google-play-music-desktop-player@3.0.0 start: `electron .`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid google-play-music-desktop-player@3.0.0
16 verbose cwd /home/parker/build/Google-Play-Music-Desktop-Player-UNOFFICIAL-
17 error Linux 4.4.3-1-ARCH
18 error argv "/usr/bin/node" "/usr/bin/npm" "start"
19 error node v5.7.1
20 error npm  v3.8.0
21 error code ELIFECYCLE
22 error google-play-music-desktop-player@3.0.0 start: `electron .`
22 error Exit status 1
23 error Failed at the google-play-music-desktop-player@3.0.0 start script 'electron .'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the google-play-music-desktop-player package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron .
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs google-play-music-desktop-player
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls google-play-music-desktop-player
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
````

When running npm install I did get a few warnings

````
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@0.9.2: Grunt needs your help! See https://github.com/gruntjs/grunt/issues/1403.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
````

**Comment by tasgoon** [comment]
I'm running Arch and also getting the same issue. Initially it complained about electron not installed, so I installed it through the AUR, and now it's giving me the same error as above.

**Comment by flakeparadigm** [comment]
Not sure the exact series of commands either of you are running, but I've found that you also need to run `npm run build`.

**Comment by parkerlreed** [comment]
Okay that partially cleared it up...

````
[parker@x3720 Google-Play-Music-Desktop-Player-UNOFFICIAL-]$ npm start

> google-play-music-desktop-player@3.0.0 start /home/parker/build/Google-Play-Music-Desktop-Player-UNOFFICIAL-
> electron .

App threw an error when running { [Error: EACCES: permission denied, mkdir '/var/local/GPMDP_STORE']
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/var/local/GPMDP_STORE' }
A JavaScript error occurred in the main process
Uncaught Exception:
Error: EACCES: permission denied, mkdir '/var/local/GPMDP_STORE'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:842:18)
    at Function.sync (/home/parker/build/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/mkdirp/index.js:71:13)
    at new Settings (/home/parker/build/Google-Play-Music-Desktop-Player-UNOFFICIAL-/build/main/utils/Settings.js:39:24)
    at /home/parker/build/Google-Play-Music-Desktop-Player-UNOFFICIAL-/build/index.js:66:21
    at Object.<anonymous> (/home/parker/build/Google-Play-Music-Desktop-Player-UNOFFICIAL-/build/index.js:118:3)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
````

I'd rather not run this as root.

**Comment by flakeparadigm** [comment]
#209 has a fix for this. If you clone his branch and use that, it'll create and use ~/.GPMDP_STORE instead.

**Comment by parkerlreed** [comment]
Also as per the original issue 

````
To get started just pull the repo and run the following

npm install
npm start
````

That's all the Readme mentions.

**Comment by parkerlreed** [comment]
Oh ffs. Trying https://github.com/devTristan/Google-Play-Music-Desktop-Player-UNOFFICIAL-

````
[parker@x3720 Google-Play-Music-Desktop-Player-UNOFFICIAL-]$ npm start

> google-play-music-desktop-player@3.0.0 start /home/parker/build/test/Google-Play-Music-Desktop-Player-UNOFFICIAL-
> electron .

####################################
############### ERROR ##############
######### LASTFM  API KEYS #########
######## HAVE NOT BEEN SET #########
#####################################
````

Do I really have to set that? It doesn't do anything else but display that message.

**Comment by MarshallOfSound** [comment]
@parkerlreed You don't have to set the API keys.  That's just a thing to warn you before packaging the application for release

**Comment by parkerlreed** [comment]
Then how do I JUST run this on Linux?

**Comment by MarshallOfSound** [comment]
Well it should be running if you are on that PR branch?

That error isn't actually an error it's just me logging a load of stuff.  I'm just booting up an ubuntu VM now so I'll have more info shortly.

**Comment by parkerlreed** [comment]
Ok. I'm on Arch using i3-wm and no UI loads. It seems to just stop at that message.

**Comment by MarshallOfSound** [comment]
Closing this issue as the original "cant start the app" problem has been resolved.  I am not familiar with arch but if you want some help getting rid of the black screen I would suggest using the electron issues thread
