### ISSUE TITLE
Uncaught Exception: Command failed: 4294967295

### ISSUE THREAD

**Issue by pcjl** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#213]
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.0
**Time:** Sat Mar 05 2016 13:56:31 GMT-0500 (Eastern Standard Time)

#### Error:
*Command failed: 4294967295*
```js
Error: Command failed: 4294967295
System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote name could not be resolved: 'update.googleplaymusicdesktopplayer.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__50`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.FileDownloader.<DownloadUrl>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerS
...Some of the stack is missing
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
This appears to be an issue with your computer not resolving my domain name.  Can you try going to http://update.googleplaymusicdesktopplayer.com/api/versions

**Comment by pcjl** [comment]
Yes, that works.

**Comment by MarshallOfSound** [comment]
OK then, I have no idea.  Does the error still appear?

**Comment by pcjl** [comment]
Nope. It just happened once. I fired up the app when I first installed and closed my laptop to sleep. When I came back, I saw the error. I haven't seen it since.

**Comment by MarshallOfSound** [comment]
Sweet, the domain was still relatively new.  Probably just a DNS propogation error

**Comment by MarshallOfSound** [comment]
Users still experiencing this error should restart the app and accept the update.  If no update is available (wait at least 10 minutes) you can download the latest release from the website like normal.

www.googleplaymusicdesktopplayer.com
