### ISSUE TITLE
Chromecast / Avahi error:  failed to map segment from shared object

### ISSUE THREAD

**Issue by andyrtr** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2237]
I have several ChromeCast devices in my LAN. They show up well on my desktop but fail on my notebook. Avahi service is running and detects the ChromeCast devices:
 avahi-browse _googlecast._tcp                                                                                                                                                                              
+ wlp2s0 IPv4 BRAVIA-4K-GB-efd797dbf83c204f63fb0f08b1c1b8df _googlecast._tcp     local

This is what is shown from command line when starting:
```

andyrtr@laptop64:/home/andyrtr $ LANG=C gpmdp --dev                                                                                                                                                                              
info: Application started.
error: Failed to load bonjour with error: {}
Bonjour is required to use Chromecast Support or to enable ZeroConf for the PlaybackAPI
On linux you need to install "avahi"
error: Uncaught Exception. Error: /tmp/.org.chromium.Chromium.9arfEi: failed to map segment from shared object
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/gpmdp/resources/app.asar/node_modules/dbus/lib/dbus.js:3:13)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/gpmdp/resources/app.asar/build/main/features/linux/mediaKeysDBus.js:11:13)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/gpmdp/resources/app.asar/build/main/features/linux/index.js:11:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/gpmdp/resources/app.asar/build/main/features/index.js:13:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at App.<anonymous> (/usr/share/gpmdp/resources/app.asar/build/index.js:184:5)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)
debug: Renderer process logger initialized.

```
OS is Arch linux x86_64. mDNS config is identical to my desktop. Can you please help me to find out if this a configuration issue or a bug?

**Comment by MarshallOfSound** [comment]
> OS is Arch linux x86_64. mDNS config is identical to my desktop.

Clearly something is different 😆  :trollface: 

I honestly have no idea, bonjour things I might be able to help with (I vaguely understand that stack) but avahi's bonjour compat layer is just beyond me.  You'd be better off generically googling for similar issues / asking in *nix forums.

AFAICS this isn't an issue with GPMDP rather an avahi issue (maybe a buggered avahi setup)

**Comment by BrianAllred** [comment]
I include instructions on how to setup avahi/mdns for Chromecast functionality in a pinned comment on the [package page](https://aur.archlinux.org/packages/gpmdp/) (and anyone who installs the package gets the instructions in bright red letters in their terminal).

This doesn't apply here since I think Andy already tried all that. Just wanted to let people know the instructions are out there, in case anyone comes across this issue trying to get things configured.

**Comment by BrianAllred** [comment]
@andyrtr After some quick Googling, that shared object error usually appears when /tmp is mounted without exec permissions. I'd try these things:

1. Verify /tmp is actually missing exec permissions. If it has exec, then we're back to square one.
2. Attempt to give /tmp exec permissions, then run GPMDP.
3. If you can't give /tmp exec permissions, then make a temporary directory that you can give exec permissions to, and export that directory as TMP before running GPMDP.

It might also be a weird thing with SELinux, so you might Google some information on how to check the SELinux log (I don't do that regularly, I have to Google it every time). 

Good luck, and let me know how it goes.

References:

https://admin-ahead.com/portal/knowledgebase/4/error-while-loading-shared-libraries-libzso1-failed-to-map-segment-from-shared-object-Operation-not-permitted.html

https://github.com/sass/node-sass/issues/1407

http://www.idmworks.com/fix-failed-map-segment-shared-object-permission-denied/
