### ISSUE TITLE
Blank Main Window

### ISSUE THREAD

**Issue by ottothecow** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2366]
Windows 7 64bit

My main window loads up blank (white screen after ~30 seconds to a minute of a loading circle) when I try to connect through my corporate network.  It seems to work OK over an open wifi network.  No error message or time out, just a blank screen.

Google Play Music works fine in Chrome on the network, but not within the desktop player.  

Is it trying to make connections on non-standard ports (different from what chrome would use)?  I can make changes to the local firewall, but obviously can't do anything to the corporate network.  For reference, Spotify's desktop player works fine.

Are there any settings I can change to force it to use a more standard port?  Or disable some check that it is doing?

Here's the log from running it with --dev:
```
"Google Play Music Desktop Player.exe" --dev

C:\Users\user\AppData\Local\GPMDP_3\app-4.2.0>
info: Application started.
Unexpected result while probing for avahi: { Error: dns service error: unknown e
rror code
    at supportsInterfaceIndexLocalOnly (C:\Users\user\AppData\Local\GPMDP_3\a
pp-4.2.0\resources\app.asar\node_modules\mdns\lib\avahi.js:17:12)
    at Object.<anonymous> (C:\Users\user\AppData\Local\GPMDP_3\app-4.2.0\reso
urces\app.asar\node_modules\mdns\lib\avahi.js:32:20)
    at Object.<anonymous> (C:\Users\user\AppData\Local\GPMDP_3\app-4.2.0\reso
urces\app.asar\node_modules\mdns\lib\avahi.js:34:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\user\AppData\Local\GPMDP_3\app-4.2.0\reso
urces\app.asar\node_modules\mdns\lib\mdns.js:31:19)
    at Object.<anonymous> (C:\Users\user\AppData\Local\GPMDP_3\app-4.2.0\reso
urces\app.asar\node_modules\mdns\lib\mdns.js:34:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\user\AppData\Local\GPMDP_3\app-4.2.0\reso
urces\app.asar\build\main\features\core\websocketAPI.js:48:10)
    at Object.<anonymous> (C:\Users\user\AppData\Local\GPMDP_3\app-4.2.0\reso
urces\app.asar\build\main\features\core\websocketAPI.js:343:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\user\AppData\Local\GPMDP_3\app-4.2.0\reso
urces\app.asar\build\main\features\core\index.js:29:1)
    at Object.<anonymous> (C:\Users\user\AppData\Local\GPMDP_3\app-4.2.0\reso
urces\app.asar\build\main\features\core\index.js:42:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\user\AppData\Local\GPMDP_3\app-4.2.0\reso
urces\app.asar\build\main\features\index.js:11:1)
    at Object.<anonymous> (C:\Users\user\AppData\Local\GPMDP_3\app-4.2.0\reso
urces\app.asar\build\main\features\index.js:14:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at App.<anonymous> (C:\Users\user\AppData\Local\GPMDP_3\app-4.2.0\resourc
es\app.asar\build\index.js:185:5)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7) errorCode: -65563 }
error: Failed to load bonjour with error: {}
Bonjour is required to use Chromecast Support or to enable ZeroConf for the Play
backAPI
On windows you need to install Bonjour Print Services
[18868:0324/123823.944:INFO:CONSOLE(73)] "Download the React DevTools and use an
 HTTP server (instead of a file: URL) for a better development experience: https
://fb.me/react-devtools", source: C:\Users\user\AppData\Local\GPMDP_3\app-4.2
.0\resources\app.asar\node_modules\react-dom\lib\ReactDOM.js (73)
[18868:0324/123824.612:INFO:CONSOLE(275)] "::shadow pseudo-element is deprecated
. See https://www.chromestatus.com/features/6750456638341120 for more details.",
 source: C:\Users\user\AppData\Local\GPMDP_3\app-4.2.0\resources\electron.asa
r\renderer\web-view\web-view.js (275)
debug: Renderer process logger initialized.
debug: Renderer process logger initialized.
```

And attached is the debug file.  This is after a fresh unistall/reinstall because I saw that suggested in another issue that was filed about a blank screen.

[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/868747/debug_info.zip)

**Comment by jostrander** [comment]
Generally speaking this has to do with the firewall not set to allow GPMDP to connect out to the network in general. Try allowing GPMDP to make connections outbound on 80 and 443 and it should be fine. It also uses port 5353 for chromecast, but it looks like you might need to install Bonjour for that as well.

**Comment by ottothecow** [comment]
That doesn't seem to have done it.  I installed Bonjour just in case that mattered, and made sure I had everything opened up in my firewall.  Added both a general permissive rule and a specific 80 and 443 rule to both inbound and outbound

![image](https://cloud.githubusercontent.com/assets/5453276/24310775/3680a362-109f-11e7-9742-820bfe4b49ed.png)

![image](https://cloud.githubusercontent.com/assets/5453276/24310873/917f4cfa-109f-11e7-90ba-27b81f69d6da.png)

And with bonjour installed, the log looks clean:


```
C:\Users\user\AppData\Local\GPMDP_3\app-4.2.0>"Google Play Music Desktop Play
er.exe" --dev

C:\Users\user\AppData\Local\GPMDP_3\app-4.2.0>
info: Application started.
[5124:0324/143024.395:INFO:CONSOLE(73)] "Download the React DevTools and use an
HTTP server (instead of a file: URL) for a better development experience: https:
//fb.me/react-devtools", source: C:\Users\user\AppData\Local\GPMDP_3\app-4.2.
0\resources\app.asar\node_modules\react-dom\lib\ReactDOM.js (73)
[5124:0324/143024.892:INFO:CONSOLE(275)] "::shadow pseudo-element is deprecated.
 See https://www.chromestatus.com/features/6750456638341120 for more details.",
source: C:\Users\user\AppData\Local\GPMDP_3\app-4.2.0\resources\electron.asar
\renderer\web-view\web-view.js (275)
debug: Renderer process logger initialized.
[5124:0324/143056.088:WARNING:backend_impl.cc(1802)] Destroying invalid entry.
debug: Renderer process logger initialized.
```

Any other ideas on what I can do to test/debug this to see where the problem is originating?  Are there any other executables I need to be granting access to?  Any way to turn on more verbose logging to see where the connection is failing?

Thanks

**Comment by MarshallOfSound** [comment]
@ottothecow Going to go out on a limb here and say your corporate network is behind a proxy.

See #921 for proxy related issues 👍 Basically not much we can do but there are a few magical args you can try to make it auto-detect your proxy
