### ISSUE TITLE
Uncaught Exception: Command failed: 4294967295

### ISSUE THREAD

**Issue by eRadicant** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#239]
Error occurred when waking up from Sleep state
Player still works fine

An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.0
**Time:** Sun Mar 06 2016 17:43:05 GMT 1100 (AUS Eastern Summer Time)

#### Error:
*Command failed: 4294967295*
```js
Error: Command failed: 4294967295
System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote name could not be resolved: 'update.googleplaymusicdesktopplayer.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__50`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.FileDownloader.<DownloadUrl>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerS
...Some of the stack is missing
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
Looks like a DNS issue, client side not in APP or on server.

Please read the log before posting to determine if it is actually an issue
