### ISSUE TITLE
Can't Run Locally on Ubuntu

### ISSUE THREAD

**Issue by blhagadorn** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2440]
I'm having a hard time getting this to run on my local ubuntu, i've installed npm, nvm, and gotten it to run on my Mac just fine.  Anyone else had similar issues? Here's my out put

```
> google-play-music-desktop-player@4.2.0 postinstall /home/trevor/Google-Play-Music-Desktop-Player-UNOFFICIAL-
> electron-rebuild --types=prod,optional

✖ Rebuild Failed
An unhandled error occurred inside electron-rebuild
make: Entering directory '/home/trevor/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/mouse-forward-back/build'
  CXX(target) Release/obj.target/mouse-forward-back/mouse-forward-back.o
../mouse-forward-back.cc:3:22: fatal error: X11/Xlib.h: No such file or directory
compilation terminated.
mouse-forward-back.target.mk:94: recipe for target 'Release/obj.target/mouse-forward-back/mouse-forward-back.o' failed
make: Leaving directory '/home/trevor/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/mouse-forward-back/build'
make: *** [Release/obj.target/mouse-forward-back/mouse-forward-back.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/trevor/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-72-generic
gyp ERR! command "/home/trevor/.nvm/versions/node/v6.5.0/bin/node" "/home/trevor/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/.bin/node-gyp" "rebuild" "--target=1.6.1" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd /home/trevor/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/mouse-forward-back
gyp ERR! node -v v6.5.0
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok 

Failed with exit code: 1

Error: make: Entering directory '/home/trevor/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/mouse-forward-back/build'
  CXX(target) Release/obj.target/mouse-forward-back/mouse-forward-back.o
../mouse-forward-back.cc:3:22: fatal error: X11/Xlib.h: No such file or directory
compilation terminated.
mouse-forward-back.target.mk:94: recipe for target 'Release/obj.target/mouse-forward-back/mouse-forward-back.o' failed
make: Leaving directory '/home/trevor/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/mouse-forward-back/build'
make: *** [Release/obj.target/mouse-forward-back/mouse-forward-back.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/trevor/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-72-generic
gyp ERR! command "/home/trevor/.nvm/versions/node/v6.5.0/bin/node" "/home/trevor/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/.bin/node-gyp" "rebuild" "--target=1.6.1" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd /home/trevor/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/mouse-forward-back
gyp ERR! node -v v6.5.0
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok 

Failed with exit code: 1
    at SafeSubscriber._error (/home/trevor/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/spawn-rx/lib/src/index.js:262:84)
    at SafeSubscriber.__tryOrUnsub (/home/trevor/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/rxjs/Subscriber.js:236:16)
    at SafeSubscriber.error (/home/trevor/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/rxjs/Subscriber.js:197:26)
    at Subscriber._error (/home/trevor/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/rxjs/Subscriber.js:128:26)
    at Subscriber.error (/home/trevor/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/rxjs/Subscriber.js:102:18)
    at MapSubscriber.Subscriber._error (/home/trevor/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/rxjs/Subscriber.js:128:26)
    at MapSubscriber.Subscriber.error (/home/trevor/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/rxjs/Subscriber.js:102:18)
    at SafeSubscriber._next (/home/trevor/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/spawn-rx/lib/src/index.js:236:65)
    at SafeSubscriber.__tryOrUnsub (/home/trevor/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/rxjs/Subscriber.js:236:16)
    at SafeSubscriber.next (/home/trevor/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/rxjs/Subscriber.js:185:22)
    at Subscriber._next (/home/trevor/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/rxjs/Subscriber.js:125:26)
    at Subscriber.next (/home/trevor/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/rxjs/Subscriber.js:89:18)
    at ReduceSubscriber._complete (/home/trevor/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/rxjs/operator/reduce.js:119:30)
    at ReduceSubscriber.Subscriber.complete (/home/trevor/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/rxjs/Subscriber.js:114:18)
    at MergeAllSubscriber.notifyComplete (/home/trevor/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/rxjs/operator/mergeAll.js:105:30)
    at InnerSubscriber._complete (/home/trevor/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/rxjs/InnerSubscriber.js:30:21)

npm WARN optional Skipping failed optional dependency //appdmg:
npm WARN notsup Not compatible with your operating system or architecture: appdmg@0.4.5
npm WARN optional Skipping failed optional dependency //ll-keyboard-hook-win:
npm WARN notsup Not compatible with your operating system or architecture: ll-keyboard-hook-win@3.0.0
npm WARN optional Skipping failed optional dependency //@nodert-win10/windows.media:
npm WARN notsup Not compatible with your operating system or architecture: @nodert-win10/windows.media@0.2.95
npm WARN optional Skipping failed optional dependency //@nodert-win10/windows.foundation:
npm WARN notsup Not compatible with your operating system or architecture: @nodert-win10/windows.foundation@0.2.95
npm WARN optional Skipping failed optional dependency //@nodert-win10/windows.media.playback:
npm WARN notsup Not compatible with your operating system or architecture: @nodert-win10/windows.media.playback@0.2.95
npm WARN optional Skipping failed optional dependency //@nodert-win10/windows.storage.streams:
npm WARN notsup Not compatible with your operating system or architecture: @nodert-win10/windows.storage.streams@0.2.95
npm WARN material-ui@0.15.4 requires a peer of react-tap-event-plugin@^1.0.0 but none was installed.
npm ERR! Linux 4.4.0-72-generic
npm ERR! argv "/home/trevor/.nvm/versions/node/v6.5.0/bin/node" "/home/trevor/.nvm/versions/node/v6.5.0/bin/npm" "install"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! google-play-music-desktop-player@4.2.0 postinstall: `electron-rebuild --types=prod,optional`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the google-play-music-desktop-player@4.2.0 postinstall script 'electron-rebuild --types=prod,optional'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the google-play-music-desktop-player package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-rebuild --types=prod,optional
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs google-play-music-desktop-player
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls google-play-music-desktop-player
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/trevor/Google-Play-Music-Desktop-Player-UNOFFICIAL-/npm-debug.log
```

**Comment by MarshallOfSound** [comment]
Simple enough, you're missing a native dependency required to build one of the modules we use for mouse button interactions.

> X11/Xlib.h

Should be fixed by install `libx11`

```bash
sudo apt-get install libx11-dev
```
