### ISSUE TITLE
Node.js LCD not displaying humidity and temperature

### ISSUE THREAD

**Issue by Chucktheduck404** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2638]
I'm trying to finish my self-water plant system. https://www.hackster.io/demirhanaydin/waterpi-houseplant-remote-watering-and-monitoring-system-340400?ref=platform&ref_id=424_respected___&offset=33. I'm on the final stages but I'm unable to get my LCD screen to display my temperature and sensor values. I'm running sudo node index.js and this is what happens. 
The raspberry pi connects and the Arduino is registered. The temperature and humidity are also registered. Then i get 

fs.js:663
return binding.writeBuffer(fd, buffer, offset, length, position);

Error: Unknown system error -121: Unkown system error -121, write 
      Then i have about 10 errors 
at Error (native)
at Object.fs.writeSync (fs.js:663:20)
at Bus.i2cWriteSync (/home/pi/waterpi-node_modules/raspi-io/node_modules/raspi-i2c/node_modules/i2c-bus/i2cbus.js:348:13
at I2c.writeSync (/home/pi/waterpi-node/node_modules/raspi-io/node_modules /raspi-i2c/dist/index.js:307:37
at RaspiIOcore.i2cWrite (/home/pi/waterpi-node/node_modules/johnny-five/lib/lcd.js:64:11
at LCD.Controllers.PCF8574.initialize.value (/home/pi/waterpi-node/node_modules/johnny-five/lib/lcd.js:362:23
at new LCD  (/home/pi/waterpi-node/node_modules/johnny-five/lib/lcd.js:783:1-
at Boards .<anonymous> (/home/pi/waterpi-node/index.js:60:9
at emit0ne (events.js:77:13)

I know that my LCD works and is being registered by my raspberry pi because I have checked using i2cdetect. I also ran a simple hello world code using python.I  tried changing the controller name of the lcd to PCF574A nothing changed . If anyone could help it would be appreciated.

**Comment by jostrander** [comment]
Uh wrong project?
