### ISSUE TITLE
postinstall script fails on Raspberry Pi

### ISSUE THREAD

**Issue by ErwinP** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2639]
Hi all,
I'm strugglin a lot to get this compiled on a Raspberry Pi 3. Most of the time I manage to get around, but I have no idea how to overcome this error:

````
pi@RaspberryPi:~/Downloads/gpmdp $ npm install
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> google-play-music-desktop-player@4.4.0 postinstall /home/pi/Downloads/gpmdp
> electron-rebuild --types=prod,optional

/home/pi/Downloads/gpmdp/node_modules/electron-rebuild/lib/src/rebuild.js:33
    constructor(lifecycle, buildPath, electronVersion, arch = process.arch, extraModules = [], forceRebuild = false, headerURL = 'https://atom.io/download/electron', types = ['prod', 'optional'], mode = defaultMode) {
                                                            ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/pi/Downloads/gpmdp/node_modules/electron-rebuild/lib/src/cli.js:16:19)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! google-play-music-desktop-player@4.4.0 postinstall: `electron-rebuild --types=prod,optional`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the google-play-music-desktop-player@4.4.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2017-07-14T14_07_03_625Z-debug.log
```

Any thoughts?

Thanks a lot in advance,
Erwin

**Comment by MarshallOfSound** [comment]
You need a newer version of nodejs.  v6+
