### ISSUE TITLE
Uncaught Exception: Cannot read property '1' of null

### ISSUE THREAD

**Issue by bornxlo** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2693]
An uncaught exception was reported.  
#### Info:
**OS:** linux
**Arch:** x64
**GPMDP Version:** 3.3.0
**Time:** Mon Aug 07 2017 18:26:39 GMT 0200 (CEST)

#### Error:
*Cannot read property '1' of null*
```js
TypeError: Cannot read property '1' of null
    at Request._callback (/usr/share/google-play-music-desktop-player/resources/app/build/main/features/core/lyrics/source_lyricsFreak.js:9:1201)
    at Request.self.callback (/usr/share/google-play-music-desktop-player/resources/app/node_modules/request/request.js:200:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/share/google-play-music-desktop-player/resources/app/node_modules/request/request.js:1067:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/share/google-play-music-desktop-player/resources/app/node_modules/request/request.js:988:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
Wow, the unicorn is still alive 😆 @jostrander it lives 👍 

@bornxlo You are almost a year out of date 😄 We are up to `4.4.0` now, please update your GPMDP

**Comment by bornxlo** [comment]
It still works, and hasn't automatically updated with the rest of my system updates, so I haven't thought to look at more recent versions. Thanks for the quick reply.

**Comment by BrianAllred** [comment]
If you're on Arch Linux, the name of the package changed at some point from `google-play-music-desktop-player` to `gpmdp`. I don't remember the version I made the change at, but you should be able to uninstall the old package and install the new one without any issues.
