### ISSUE TITLE
Starting GPMDP w/o internet is blank. 

### ISSUE THREAD

**Issue by AlcaDesign** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2714]
**OS:** Windows 7

**Issue Descriptions:** Starting GPMDP without network access (completely disconnected) results in a blank app. You must ensure the network is up and then close and open GPMDP again. Similar to #1298 but it's definitely still blank for me after 414364b3388245def1a3ec70ca94cd00838c0f15.

**Proposal:** Detect network availability and attempt to reload once available again. Also show _anything_ instead of a blank screen if possible with a useful error message regarding the network access and perhaps a "try now" button to attempt a manual reload.

**Steps to Reproduce:**

0. Start with GPMDP closed.
1. Disable the network.
2. Load GPMDP.

```
C:\>set ELECTRON_ENABLE_LOGGING=true
C:\>set ELECTRON_ENABLE_STACK_DUMPING=true
C:\>"%LOCALAPPDATA%\GPMDP_3\app-4.4.0\Google Play Music Desktop Player.exe" --dev

C:\>
info: Application started.
[1740:0819/180113.152:WARNING:dns_config_service_win.cc(661)] Failed to read DnsConfig.
Unexpected result while probing for avahi: { Error: dns service error: unknown error code
    at supportsInterfaceIndexLocalOnly (C:\Users\Alca\AppData\Local\GPMDP_3\app-4.4.0\resources\app.asar\node_modules\mdns\lib\avahi.js:17:12)
    at Object.<anonymous> (C:\Users\Alca\AppData\Local\GPMDP_3\app-4.4.0\resources\app.asar\node_modules\mdns\lib\avahi.js:32:20)
    at Object.<anonymous> (C:\Users\Alca\AppData\Local\GPMDP_3\app-4.4.0\resources\app.asar\node_modules\mdns\lib\avahi.js:34:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Alca\AppData\Local\GPMDP_3\app-4.4.0\resources\app.asar\node_modules\mdns\lib\mdns.js:31:19)
    at Object.<anonymous> (C:\Users\Alca\AppData\Local\GPMDP_3\app-4.4.0\resources\app.asar\node_modules\mdns\lib\mdns.js:34:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Alca\AppData\Local\GPMDP_3\app-4.4.0\resources\app.asar\build\main\features\core\websocketAPI.js:48:10)
    at Object.<anonymous> (C:\Users\Alca\AppData\Local\GPMDP_3\app-4.4.0\resources\app.asar\build\main\features\core\websocketAPI.js:345:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Alca\AppData\Local\GPMDP_3\app-4.4.0\resources\app.asar\build\main\features\core\index.js:29:1)
    at Object.<anonymous> (C:\Users\Alca\AppData\Local\GPMDP_3\app-4.4.0\resources\app.asar\build\main\features\core\index.js:44:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Alca\AppData\Local\GPMDP_3\app-4.4.0\resources\app.asar\build\main\features\index.js:11:1)
    at Object.<anonymous> (C:\Users\Alca\AppData\Local\GPMDP_3\app-4.4.0\resources\app.asar\build\main\features\index.js:14:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at App.<anonymous> (C:\Users\Alca\AppData\Local\GPMDP_3\app-4.4.0\resources\app.asar\build\index.js:185:5)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7) errorCode: -65563 }
error: Failed to load bonjour with error: {}
Bonjour is required to use Chromecast Support or to enable ZeroConf for the PlaybackAPI
On windows you need to install Bonjour Print Services
error: Could not initialize bonjour service with error: {}
error: ################### !! Update server down !! ##################
[1740:0819/180114.387:INFO:CONSOLE(73)] "Download the React DevTools and use an HTTP server (instead of a file: URL) for a better development experience: https://fb.me/react-devtools", source: C:\Users\Alca\AppData\Local\GPMDP_3\app-4.4.0\resources\app.asar\node_modules\react-dom\lib\ReactDOM.js (73)
[1740:0819/180114.467:INFO:CONSOLE(40)] "Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs", source: C:\Users\Alca\AppData\Local\GPMDP_3\app-4.4.0\resources\app.asar\node_modules\react\lib\lowPriorityWarning.js (40)
[1740:0819/180114.850:INFO:CONSOLE(275)] "::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.",
source: C:\Users\Alca\AppData\Local\GPMDP_3\app-4.4.0\resources\electron.asar\renderer\web-view\web-view.js (275)
debug: Renderer process logger initialized.
debug: Renderer process logger initialized.
[1740:0819/180118.154:WARNING:dns_config_service_win.cc(661)] Failed to read DnsConfig.
[1740:0819/180123.157:WARNING:dns_config_service_win.cc(661)] Failed to read DnsConfig.
[1740:0819/180128.160:WARNING:dns_config_service_win.cc(661)] Failed to read DnsConfig.
[1740:0819/180133.163:WARNING:dns_config_service_win.cc(661)] Failed to read DnsConfig.
[1740:0819/180138.166:WARNING:dns_config_service_win.cc(661)] Failed to read DnsConfig.
[1740:0819/180143.170:WARNING:dns_config_service_win.cc(661)] Failed to read DnsConfig.
```

**Comment by MarshallOfSound** [comment]
@AlcaDesign Looks like you're experiencing an Electron bug where the renderer process crashes if you don't have an active network connection.  It's a weird bug that's been around for a while but is super rare.  Not much I can do about it on this end unfortunately
