### ISSUE TITLE
Uncaught Exception: Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by JonBons** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#282]
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.0
**Time:** Sun Mar 06 2016 14:01:57 GMT-0600 (Central Standard Time)

#### Error:
*Error: spawn UNKNOWN*
```js
Error: Error: spawn UNKNOWN
    at AutoUpdater.emitError (C:\Users\JonBons\AppData\Local\GPMDP_3\app-3.0.0\resources\atom.asar\browser\api\lib\auto-updater\auto-updater-win.js:58:31)
    at C:\Users\JonBons\AppData\Local\GPMDP_3\app-3.0.0\resources\atom.asar\browser\api\lib\auto-updater\auto-updater-win.js:32:24
    at C:\Users\JonBons\AppData\Local\GPMDP_3\app-3.0.0\resources\atom.asar\browser\api\lib\auto-updater\squirrel-update-win.js:70:14
    at C:\Users\JonBons\AppData\Local\GPMDP_3\app-3.0.0\resources\atom.asar\browser\api\lib\auto-updater\squirrel-update-win.js:26:14
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
Closing and moving to electron repo as bug
