### ISSUE TITLE
Uncaught Exception when opening app; Desktop Settings don't work

### ISSUE THREAD

**Issue by andregodoy0** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2859]
**OS:** Ubuntu 16.04 LTS
`$: uname -srvoi`
`Linux 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 GNU/Linux`

**Issue Descriptions:**
When opening the app I see the following error:
```
Uncaught Exception:
Error: EIO: i/o error, write
    at Object.fs.writeSync (fs.js:719:20)
    at SyncWriteStream._write (internal/fs.js:75:6)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at SyncWriteStream.Writable.write (_stream_writable.js:245:11)
    at Console.log (console.js:43:16)
    at Object.<anonymous> (/usr/share/google-play-music-desktop-player/resources/app.asar/build/main/features/core/errorHandler.js:43:11)
    at Object.<anonymous> (/usr/share/google-play-music-desktop-player/resources/app.asar/build/main/features/core/errorHandler.js:69:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/google-play-music-desktop-player/resources/app.asar/build/main/features/core/index.js:11:1)
    at Object.<anonymous> (/usr/share/google-play-music-desktop-player/resources/app.asar/build/main/features/core/index.js:44:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/google-play-music-desktop-player/resources/app.asar/build/main/features/index.js:11:1)
    at Object.<anonymous> (/usr/share/google-play-music-desktop-player/resources/app.asar/build/main/features/index.js:14:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at App.<anonymous> (/usr/share/google-play-music-desktop-player/resources/app.asar/build/index.js:186:5)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)
```

The app opens after that, but previously assigned hotkeys don't work neither the button to open the "Desktop Settings" button. The app also don't save the state of last opened Artist/Radio/Playlist, it stays on the last viewed page before the crash started happening. All other features work as expected (except the mini player, it freezes the app if I try to switch to it).

**Steps to Reproduce:**
Not sure, it started after a while using the app, now happens every time I open it.

**Comment by MarshallOfSound** [comment]
> Error: EIO: i/o error, write

Looks like your drive has some issues 😆 That error is coming straight from the OS as we try read/write the settings file.  You should look into why that error is happening on your device 👍

**Comment by cprpopqual** [comment]
I'm also seeing this on 4.5.0 (just attempted to upgrade from 4.3.0). I'm on Ubuntu LTS 16.04.3 LTS.

I'm not seeing any issues with `~/.config/Google Play Music Desktop Player/json_store/.settings.json`, I can read it from console.

I've attached the exception trace.

[exception.txt](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/1716552/exception.txt)
