### ISSUE TITLE
Update to Node 8.5.4 broke the dbus module

### ISSUE THREAD

**Issue by RAOF** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2993]
**OS:** Linux (Snap)

**Issue Descriptions:** DBus module fails to load with a console error message on startup; features which use this (MPRIS, etc) don't work.

**Steps to Reproduce:** (Once the snap has built in the store) Install version 4.5.0 from the `edge` channel of the Snap store. It will start, but fail to appear in the Sound Menu.

Changing `node-engine` back to `7.2.0` results in the dbus module being correctly loaded.

**Comment by jostrander** [comment]
What's the console error message?

**Comment by RAOF** [comment]
```
error: Uncaught Exception. Error: Cannot find module 'dbus'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/snap/google-play-music-desktop-player/x5/google-play-music-desktop-player/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/snap/google-play-music-desktop-player/x5/google-play-music-desktop-player/resources/app.asar/build/main/features/linux/mediaKeysDBus.js:11:13)
    at Object.<anonymous> (/snap/google-play-music-desktop-player/x5/google-play-music-desktop-player/resources/app.asar/build/main/features/linux/mediaKeysDBus.js:48:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/snap/google-play-music-desktop-player/x5/google-play-music-desktop-player/resources/app.asar/build/main/features/linux/index.js:11:1)
    at Object.<anonymous> (/snap/google-play-music-desktop-player/x5/google-play-music-desktop-player/resources/app.asar/build/main/features/linux/index.js:14:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/snap/google-play-music-desktop-player/x5/google-play-music-desktop-player/resources/app.asar/build/main/features/index.js:13:1)
    at Object.<anonymous> (/snap/google-play-music-desktop-player/x5/google-play-music-desktop-player/resources/app.asar/build/main/features/index.js:14:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at App.<anonymous> (/snap/google-play-music-desktop-player/x5/google-play-music-desktop-player/resources/app.asar/build/index.js:183:5)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:194:7)
```

**Comment by RAOF** [comment]
DBus *does* seem to be being built during the build:
...
```
> dbus@0.2.18 install /root/build_google-play-music-desktop-player/parts/google-play-music-desktop-player/build/node_modules/dbus
> node-gyp configure build

make: Entering directory '/root/build_google-play-music-desktop-player/parts/google-play-music-desktop-player/build/node_modules/dbus/build'
  CXX(target) Release/obj.target/dbus/src/dbus.o
  CXX(target) Release/obj.target/dbus/src/connection.o
  CXX(target) Release/obj.target/dbus/src/signal.o
  CXX(target) Release/obj.target/dbus/src/encoder.o
  CXX(target) Release/obj.target/dbus/src/decoder.o
  CXX(target) Release/obj.target/dbus/src/introspect.o
  CXX(target) Release/obj.target/dbus/src/object_handler.o
  SOLINK_MODULE(target) Release/obj.target/dbus.node
  COPY Release/dbus.node
make: Leaving directory '/root/build_google-play-music-desktop-player/parts/google-play-music-desktop-player/build/node_modules/dbus/build'
```

**Comment by RAOF** [comment]
For what it's worth, it also fails with Node 9.5.0

**Comment by jostrander** [comment]
Can you share the entire build log for node 7/8/9?

**Comment by RAOF** [comment]
Node 9.5.0 build log: https://paste.ubuntu.com/26539174/
(I trimmed the snapcraft setup bit above that log; if you want full-full logs including all the .deb package downloads I can provide that, too)

**Comment by RAOF** [comment]
Node 8.9.4 build: http://paste.ubuntu.com/26539182/

**Comment by RAOF** [comment]
Node 7.2.0 build: http://paste.ubuntu.com/26539231/

**Comment by jostrander** [comment]
Struggling to find any build differences in there, other than some deprecations in node 9/nan. They all appear to build dbus fine.

**Comment by jostrander** [comment]
I'm curious as to if there are any package differences being installed when using npm, as there is no `package-lock.json`, but only a `yarn.lock`. Can we test using `node-package-manager: yarn`?

**Comment by RAOF** [comment]
Hm. We use the `gulp` plugin rather than the `nodejs` plugin and so we don't have that knob.

I can try adding that to the `gulp` plugin and see...

**Comment by jostrander** [comment]
The alternative may be to add a `package-lock.json` to the repo, but I'm not sure what @MarshallOfSound's stance is on that.

**Comment by RAOF** [comment]
It's being super annoying to try and switch the `gulp` plugin to use `yarn`. How could I test adding a `package-lock.json`?

**Comment by MarshallOfSound** [comment]
Closing this out for now as it's a discussion thread tangental to the project itself, as for adding a `package-lock.json` I'm not a fan, yarn's the thing for me 😄

**Comment by RAOF** [comment]
We should probably keep *one* of the “why is 4.5.0 not published to the snap stable channel” bugs open. I don't really care which one 😀
