### ISSUE TITLE
Remote release file is empty or corrupted

### ISSUE THREAD

**Issue by Stanzilla** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2999]
Was wondering why GPMDP was not updating and checked my Squirrel log file:

```
2018-02-10 01:41:17> FileDownloader: Downloading url: https://update.gpmdp.xyz/update/win/4.5.0/RELEASES?id=GPMDP_3&localVersion=4.5.0&arch=amd64
2018-02-10 01:41:18> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.Exception: Remote release File is empty or corrupted
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.Exception: Remote release File is empty or corrupted
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()<---

```

**Comment by MarshallOfSound** [comment]
There has been an intermittent outage of the update server over the last few days, everything should still be working fine though 👍

**Comment by Stanzilla** [comment]
Well that was from just now, so it is still happening?

**Comment by MarshallOfSound** [comment]
@Stanzilla What happens when you go to https://update.gpmdp.xyz/update/win/4.5.0/RELEASES?id=GPMDP_3&localVersion=4.5.0&arch=amd64 in your browser?

**Comment by Stanzilla** [comment]
@MarshallOfSound downloads a releases file with this content

``` 
33601A715D088E1C77158702E5DE966E22AC27DE http://update.gpmdp.xyz/download/4.1.1/GPMDP_3-4.1.1-delta.nupkg 1855310
8785F729C6C696231230427BA64A3F1298906EA1 http://update.gpmdp.xyz/download/4.1.1/GPMDP_3-4.1.1-full.nupkg 54936818
50EA6E6A6EB7D6275BEDAB4043FC190155AD5572 http://update.gpmdp.xyz/download/4.2.0/GPMDP_3-4.2.0-delta.nupkg 27471424
B66357E5CD448A46C6C0303EBBE07494338A2CB7 http://update.gpmdp.xyz/download/4.2.0/GPMDP_3-4.2.0-full.nupkg 55433556
ED866230066BD29920E9C7BA9C480D8C0138668C http://update.gpmdp.xyz/download/4.3.0/GPMDP_3-4.3.0-delta.nupkg 7658256
1A3191EB8E959B6E74367D1FD380E95C31113FB4 http://update.gpmdp.xyz/download/4.3.0/GPMDP_3-4.3.0-full.nupkg 63518065
4F34C6D4D34805FEC63FCC2D31169EF72CA275E7 http://update.gpmdp.xyz/download/4.4.0/GPMDP_3-4.4.0-delta.nupkg 13266354
2069F8869189D9ACD15F915830F26E5CEB345847 http://update.gpmdp.xyz/download/4.4.0/GPMDP_3-4.4.0-full.nupkg 56268075
30C5EC297E4888E6DF291FB606A3DA3F5E6ACFEE http://update.gpmdp.xyz/download/4.4.1/GPMDP_3-4.4.1-delta.nupkg 229245
9CB82CA73B6B292B310536BB7F872A778FF6C341 http://update.gpmdp.xyz/download/4.4.1/GPMDP_3-4.4.1-full.nupkg 56085556
50FA7661206AC3CB1F5356A1040AA95E826341B6 http://update.gpmdp.xyz/download/4.5.0/GPMDP_3-4.5.0-delta.nupkg 19912566
A23A912C1F86979D0ACDC1A2B030F7814A9DA733 http://update.gpmdp.xyz/download/4.5.0/GPMDP_3-4.5.0-full.nupkg 59124589
```

maybe I hit the cache before
