### ISSUE TITLE
Uncaught Exception: Command failed: 4294967295

### ISSUE THREAD

**Issue by 19007361** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#323]
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.0
**Time:** Mon Mar 07 2016 10:24:33 GMT 0200 (South Africa Standard Time)

#### Error:
*Command failed: 4294967295*
```js
Error: Command failed: 4294967295
System.AggregateException: One or more errors occurred. ---> System.Exception: Invalid release entry: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
   at Squirrel.ReleaseEntry.ParseReleaseEntry(String entry)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Squirrel.ReleaseEntry.ParseReleaseFile(String fileContents)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAw
...Some of the stack is missing
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
Funky updater errors #yolo

**Comment by 19007361** [comment]
I just posted this because the program was bugging me to report it the whole time.

**Comment by MarshallOfSound** [comment]
Yeah, in the next update I'm going to stop any errors related to the updater popping up :+1:

**Comment by 19007361** [comment]
It wasn't a criticism, was just saying. It's a cool feature.

**Comment by MarshallOfSound** [comment]
I know, but I'm getting spammed with issues I'm just closing because they are just network issues
