### ISSUE TITLE
Uncaught Exception: Error processing argument -1.

### ISSUE THREAD

**Issue by SoylentG** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#326]
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.0
**Time:** Mon Mar 07 2016 10:57:04 GMT 0100 (W. Europe Standard Time)

#### Error:
*Error processing argument -1.*
```js
TypeError: Error processing argument -1.
    at TypeError (native)
    at EventEmitter.<anonymous> (C:\Users\***\AppData\Local\GPMDP_3\app-3.0.0\resources\app\build\main\features\core\keyboardShotcuts.js:47:56)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.<anonymous> (C:\Users\***\AppData\Local\GPMDP_3\app-3.0.0\resources\atom.asar\browser\api\lib\web-contents.js:120:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
You managed to set an invalid shortcut for something?

What did you try set it to?

**Comment by SoylentG** [comment]
Alt+ Num keys, same as CTRL + Num keys. Then it completely bugs out for me, every key I press throws this exception then and ESC removes it, but when I re-open the settings the bugged key is still there.

**Comment by MarshallOfSound** [comment]
Might want to just delete the settings file and start again :/

**Comment by SoylentG** [comment]
Will do, might want to only allow certain keys for shortcuts (am using a german keyboard, so this might not occur on US/UK ones). Love the program though! :D

**Comment by MarshallOfSound** [comment]
Thanks!
