### ISSUE TITLE
Install Mini Player -> Squirrel Update client fails

### ISSUE THREAD

**Issue by thepigeonfighter** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3412]
**Checklist:**

* [ X] I have checked that there are no issues with similar or the same content
* [X ] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [X ] I have double checked and can reproduce the issue

**OS:**
Windows 10
**GPMDP Version:**
V4.5.0
**Issue Descriptions:**
Program asked me to install mini player. I click install program gets stuck. The squirrel update process throws an exception saying that the remote update is either empty or corrupted
**Steps to Reproduce:**
1 Open Program
2 Program Asks me to install mini player
![untitled](https://user-images.githubusercontent.com/33707144/47954428-72c27080-df60-11e8-8217-5ac46baad0c8.png)
3 Clicked install
![untitled1](https://user-images.githubusercontent.com/33707144/47954475-bcab5680-df60-11e8-9e73-df4ee5e3244a.png)
4 This is the debug output 
--------------------------------------------------------------------------------------
2018-11-03 11:36:05> Program: Starting Squirrel Updater: --checkForUpdate https://update.gpmdp.xyz/update/win/4.5.0
2018-11-03 11:36:05> Program: Fetching update information, downloading from https://update.gpmdp.xyz/update/win/4.5.0
2018-11-03 11:36:05> CheckForUpdateImpl: Using existing staging user ID: 30c0940b-22bf-588e-b002-ec1609bd9062
2018-11-03 11:36:05> CheckForUpdateImpl: Downloading RELEASES file from https://update.gpmdp.xyz/update/win/4.5.0
2018-11-03 11:36:05> FileDownloader: Downloading url: https://update.gpmdp.xyz/update/win/4.5.0/RELEASES?id=GPMDP_3&localVersion=4.6.1&arch=amd64
2018-11-03 11:36:07> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.Exception: Remote release File is empty or corrupted
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.Exception: Remote release File is empty or corrupted
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()<---

**Comment by MarshallOfSound** [comment]
> Program asked me to install mini player.

You clicked the mini player button somewhere that google provides, not our mini player button.  The Squirrel error is unrelated to this issue.  The new mini player button is hidden on master but not yet released, please ensure you click the mini player button in the bottom right corner of the player
