### ISSUE TITLE
Uncaught Exception: UNKNOWN: unknown error, open 'C:\Users\usuario\AppData\Roaming\GPMDP_STORE\playback.json'

### ISSUE THREAD

**Issue by alberttoi** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3522]
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.0
**Time:** Mon Mar 11 2019 22:17:48 GMT-0600 (Hora de verano de las Montañas)

#### Error:
*UNKNOWN: unknown error, open 'C:\Users\usuario\AppData\Roaming\GPMDP_STORE\playback.json'*
```js
Error: UNKNOWN: unknown error, open 'C:\Users\usuario\AppData\Roaming\GPMDP_STORE\playback.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:159:20)
    at Object.fs.writeFileSync (fs.js:1234:33)
    at PlaybackAPI._save (C:\Users\usuario\AppData\Local\GPMDP_3\app-3.0.0\resources\app\build\main\utils\PlaybackAPI.js:81:20)
    at PlaybackAPI.setTime (C:\Users\usuario\AppData\Local\GPMDP_3\app-3.0.0\resources\app\build\main\utils\PlaybackAPI.js:120:12)
    at EventEmitter.<anonymous> (C:\Users\usuario\AppData\Local\GPMDP_3\app-3.0.0\resources\app\build\main\utils\PlaybackAPI.js:56:15)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.<anonymous> (C:\Users\usuario\AppData\Local\GPMDP_3\app-3.0.0\resources\atom.asar\browser\api\lib\web-contents.js:120:25)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by jostrander** [comment]
You are running a severely outdated version, please update.
