### ISSUE TITLE
Cannot install on Fedora 23 x64

### ISSUE THREAD

**Issue by martinoj2009** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#354]
**OS:** Fedora 23 x64

**Issue Descriptions:** How to install on Fedora

**Steps to Reproduce:**

I've never used npm, how do I install this on Fedora 23 x64? I tried doing npm run build:

> google-play-music-desktop-player@3.0.0 build /home/martino/Google-Play-Music-Desktop-Player-UNOFFICIAL-
> gulp build

/home/martino/Google-Play-Music-Desktop-Player-UNOFFICIAL-/gulpfile.js:3
const _ = require('lodash');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/home/martino/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/home/martino/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/home/martino/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/home/martino/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/gulp/node_modules/liftoff/index.js:185:9)
npm ERR! weird error 8
npm ERR! not ok code 0

**Comment by MarshallOfSound** [comment]
You need `node.js` 4.0 and above.

From the error log it looks like you are running node `0.12.X`
