### ISSUE TITLE
Websocket API "Connection reset by peer"

### ISSUE THREAD

**Issue by aiguofer** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3637]
**OS:** Ubuntu

**GPMDP Version:** 4.6.1-1

**Issue Descriptions:** I can't connect to the websocket API anymore. When I try to, it just gives me the` "Connection reset by peer"` error

**Steps to Reproduce:**
Run the following in python:

```
$ python
>>> import websocket
>>> websocket.create_connection("ws://localhost:5672")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aiguofer/.pyenv/versions/default2/local/lib/python2.7/site-packages/websocket/_core.py", line 514, in create_connection
    websock.connect(url, **options)
  File "/home/aiguofer/.pyenv/versions/default2/local/lib/python2.7/site-packages/websocket/_core.py", line 226, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/aiguofer/.pyenv/versions/default2/local/lib/python2.7/site-packages/websocket/_handshake.py", line 79, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/aiguofer/.pyenv/versions/default2/local/lib/python2.7/site-packages/websocket/_handshake.py", line 158, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/home/aiguofer/.pyenv/versions/default2/local/lib/python2.7/site-packages/websocket/_http.py", line 305, in read_headers
    line = recv_line(sock)
  File "/home/aiguofer/.pyenv/versions/default2/local/lib/python2.7/site-packages/websocket/_socket.py", line 123, in recv_line
    c = recv(sock, 1)
  File "/home/aiguofer/.pyenv/versions/default2/local/lib/python2.7/site-packages/websocket/_socket.py", line 102, in recv
    bytes_ = _recv()
  File "/home/aiguofer/.pyenv/versions/default2/local/lib/python2.7/site-packages/websocket/_socket.py", line 84, in _recv
    return sock.recv(bufsize)
socket.error: [Errno 104] Connection reset by peer
```

**Comment by aiguofer** [comment]
Figured out my problem.

I ran `netstat -lntup | grep :5672` and found that the port was in use by process `beam.smp`. After googling, I found out that's part of RabbitMQ. I stopped and disabled the systemd unit for RabbitMQ (I can just use Docker whenever I need it for development). After that I restarted GPMDP and everything is good again :)
