### ISSUE TITLE
Uncaught Exception: Could not get code signature for running application

### ISSUE THREAD

**Issue by chrismou** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#370]
Got the following while booting up GPMDP via terminal using `npm start`

Based on latest `master` (as of 13:00GMT 8/3/16)

It prompted me to log it on Github, so here I am ;-)

#####

An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Tue Mar 08 2016 12:59:35 GMT 0000 (GMT)

#### Error:
*Could not get code signature for running application*
```js
Error: Could not get code signature for running application
    at Error (native)
    at /Users/xxx/Dev/Google-Play-Music-Desktop-Player-UNOFFICIAL-/build/main/features/core/autoUpdater.js:19:29
    at setUpAutoUpdate (/Users/xxx/Dev/Google-Play-Music-Desktop-Player-UNOFFICIAL-/build/main/features/core/autoUpdater.js:58:7)
    at ClientRequest.<anonymous> (/Users/xxx/Dev/Google-Play-Music-Desktop-Player-UNOFFICIAL-/build/main/features/core/autoUpdater.js:66:5)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:421:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at Socket.socketOnData (_http_client.js:311:20)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
All good, this just means that Squirrel can't fetch any updates (or try to update) without the app being codesigned.  That's why it doesn't happen on release versions :+1:
