### ISSUE TITLE
Library doesnt load

### ISSUE THREAD

**Issue by vikktorpenchev** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3747]
Hello there,
Desktop player doesn't load library, stuck on "music library is loading"

**OS:**
Windows 10

**GPMDP Version:**
v4.6.1
![Capture](https://user-images.githubusercontent.com/30308653/71319278-a9c94d80-24a4-11ea-8c96-a23dcc834a1a.PNG)

**Issue Descriptions:**
when I start the player, it shows the screen with text Loading music library, but doesn't start. I assume I have to give access to app.

**Steps to Reproduce:**
Start the player, login.

**Comment by Gelunox** [comment]
I'm also having this issue. YouTube music still works though.

**Comment by olympy** [comment]
Me too. Even after I have redownloaded and updated app.
![image](https://user-images.githubusercontent.com/1076878/71322400-d9417f80-24cf-11ea-9c80-fc51a6c22da9.png)

**Comment by Zumochi** [comment]
Experiencing the same issue :(

**Comment by Zumochi** [comment]
In the SquirrelSetup.log file I can see the following exception occur sometimes:
```2019-12-15 20:46:43> FileDownloader: Downloading url: https://update.gpmdp.xyz/update/win/4.6.1/RELEASES?id=GPMDP_3&localVersion=4.6.1&arch=amd64
2019-12-15 20:46:44> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.Exception: Remote release File is empty or corrupted
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.Exception: Remote release File is empty or corrupted
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()<---```
The last line before the exception is always where it stops loading.

**Comment by jostrander** [comment]
Duplicate #3660
