### ISSUE TITLE
IOException during update to 3.0.0

### ISSUE THREAD

**Issue by ajhodges** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#375]
Just wanted to report this.

**OS:**
Windows 7 Enterprise

**Issue Descriptions:**
Updating from 2.1.1 -> 3.0.0. Got a pop up when I opened the player saying the update was available. Downloaded and attempted to install the update, and got this error:

```
2015-12-10 14:53:07> Program: Starting Squirrel Updater: --install .
2015-12-10 14:53:07> Program: Starting install, writing to C:\Users\ahodges\AppData\Local\SquirrelTemp
2015-12-10 14:53:07> Program: About to install to: C:\Users\ahodges\AppData\Local\slack
2015-12-10 14:53:07> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\ahodges\AppData\Local\slack\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3f.MoveNext()
2015-12-10 14:53:07> CheckForUpdateImpl: Reading RELEASES file from C:\Users\ahodges\AppData\Local\SquirrelTemp
2015-12-10 14:53:07> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2015-12-10 14:53:07> ApplyReleasesImpl: Writing files to app directory: C:\Users\ahodges\AppData\Local\slack\app-1.2.7
2015-12-10 14:53:10> ApplyReleasesImpl: Moving file C:\Users\ahodges\AppData\Local\slack\app-1.2.7\lib\net45\Akavache.Deprecated.dll to C:\Users\ahodges\AppData\Local\slack\app-1.2.7\Akavache.Deprecated.dll
2015-12-10 14:53:10> ApplyReleasesImpl: Moving file C:\Users\ahodges\AppData\Local\slack\app-1.2.7\lib\net45\Akavache.dll to C:\Users\ahodges\AppData\Local\slack\app-1.2.7\Akavache.dll
2015-12-10 14:53:10> ApplyReleasesImpl: Moving file C:\Users\ahodges\AppData\Local\slack\app-1.2.7\lib\net45\boringssl.dll to C:\Users\ahodges\AppData\Local\slack\app-1.2.7\boringssl.dll
2015-12-10 14:53:10> ApplyReleasesImpl: Moving file C:\Users\ahodges\AppData\Local\slack\app-1.2.7\lib\net45\CallsCore.dll to C:\Users\ahodges\AppData\Local\slack\app-1.2.7\CallsCore.dll
2015-12-10 14:53:10> ApplyReleasesImpl: Moving file C:\Users\ahodges\AppData\Local\slack\app-1.2.7\lib\net45\content_resources_200_percent.pak to C:\Users\ahodges\AppData\Local\slack\app-1.2.7\content_resources_200_percent.pak
2015-12-10 14:53:10> ApplyReleasesImpl: Moving file C:\Users\ahodges\AppData\Local\slack\app-1.2.7\lib\net45\content_shell.pak to C:\Users\ahodges\AppData\Local\slack\app-1.2.7\content_shell.pak
2015-12-10 14:53:10> ApplyReleasesImpl: Moving file C:\Users\ahodges\AppData\Local\slack\app-1.2.7\lib\net45\d3dcompiler_47.dll to C:\Users\ahodges\AppData\Local\slack\app-1.2.7\d3dcompiler_47.dll
2015-12-10 14:53:10> ApplyReleasesImpl: Moving file C:\Users\ahodges\AppData\Local\slack\app-1.2.7\lib\net45\libEGL.dll to C:\Users\ahodges\AppData\Local\slack\app-1.2.7\libEGL.dll
2015-12-10 14:53:10> ApplyReleasesImpl: Moving file C:\Users\ahodges\AppData\Local\slack\app-1.2.7\lib\net45\icudtl.dat to C:\Users\ahodges\AppData\Local\slack\app-1.2.7\icudtl.dat
2015-12-10 14:53:10> ApplyReleasesImpl: Moving file C:\Users\ahodges\AppData\Local\slack\app-1.2.7\lib\net45\libGLESv2.dll to C:\Users\ahodges\AppData\Local\slack\app-1.2.7\libGLESv2.dll
2015-12-10 14:53:10> ApplyReleasesImpl: Moving file C:\Users\ahodges\AppData\Local\slack\app-1.2.7\lib\net45\msvcp120.dll to C:\Users\ahodges\AppData\Local\slack\app-1.2.7\msvcp120.dll
2015-12-10 14:53:10> ApplyReleasesImpl: Moving file C:\Users\ahodges\AppData\Local\slack\app-1.2.7\lib\net45\natives_blob.bin to C:\Users\ahodges\AppData\Local\slack\app-1.2.7\natives_blob.bin
2015-12-10 14:53:10> ApplyReleasesImpl: Moving file C:\Users\ahodges\AppData\Local\slack\app-1.2.7\lib\net45\node.dll to C:\Users\ahodges\AppData\Local\slack\app-1.2.7\node.dll
2015-12-10 14:53:10> ApplyReleasesImpl: Moving file C:\Users\ahodges\AppData\Local\slack\app-1.2.7\lib\net45\LICENSE to C:\Users\ahodges\AppData\Local\slack\app-1.2.7\LICENSE
2015-12-10 14:53:10> ApplyReleasesImpl: Moving file C:\Users\ahodges\AppData\Local\slack\app-1.2.7\lib\net45\msvcr120.dll to C:\Users\ahodges\AppData\Local\slack\app-1.2.7\msvcr120.dll
2015-12-10 14:53:10> ApplyReleasesImpl: Moving file C:\Users\ahodges\AppData\Local\slack\app-1.2.7\lib\net45\Newtonsoft.Json.dll to C:\Users\ahodges\AppData\Local\slack\app-1.2.7\Newtonsoft.Json.dll
2015-12-10 14:53:10> ApplyReleasesImpl: Moving file C:\Users\ahodges\AppData\Local\slack\app-1.2.7\lib\net45\pdf.dll to C:\Users\ahodges\AppData\Local\slack\app-1.2.7\pdf.dll
2015-12-10 14:53:10> ApplyReleasesImpl: Moving file C:\Users\ahodges\AppData\Local\slack\app-1.2.7\lib\net45\protobuf_lite.dll to C:\Users\ahodges\AppData\Local\slack\app-1.2.7\protobuf_lite.dll
2015-12-10 14:53:10> ApplyReleasesImpl: Moving file C:\Users\ahodges\AppData\Local\slack\app-1.2.7\lib\net45\slack.exe to C:\Users\ahodges\AppData\Local\slack\app-1.2.7\slack.exe
2015-12-10 14:53:10> ApplyReleasesImpl: Moving file C:\Users\ahodges\AppData\Local\slack\app-1.2.7\lib\net45\ReactiveUI.dll to C:\Users\ahodges\AppData\Local\slack\app-1.2.7\ReactiveUI.dll
2015-12-10 14:53:10> ApplyReleasesImpl: Moving file C:\Users\ahodges\AppData\Local\slack\app-1.2.7\lib\net45\snapshot_blob.bin to C:\Users\ahodges\AppData\Local\slack\app-1.2.7\snapshot_blob.bin
2015-12-10 14:53:10> ApplyReleasesImpl: Moving file C:\Users\ahodges\AppData\Local\slack\app-1.2.7\lib\net45\PerMonitorDpi.dll to C:\Users\ahodges\AppData\Local\slack\app-1.2.7\PerMonitorDpi.dll
2015-12-10 14:53:10> ApplyReleasesImpl: Moving file C:\Users\ahodges\AppData\Local\slack\app-1.2.7\lib\net45\squirrel.exe to C:\Users\ahodges\AppData\Local\slack\app-1.2.7\squirrel.exe
2015-12-10 14:53:10> ApplyReleasesImpl: Moving file C:\Users\ahodges\AppData\Local\slack\app-1.2.7\lib\net45\Splat.dll to C:\Users\ahodges\AppData\Local\slack\app-1.2.7\Splat.dll
2015-12-10 14:53:10> ApplyReleasesImpl: Moving file C:\Users\ahodges\AppData\Local\slack\app-1.2.7\lib\net45\System.Reactive.Core.dll to C:\Users\ahodges\AppData\Local\slack\app-1.2.7\System.Reactive.Core.dll
2015-12-10 14:53:10> ApplyReleasesImpl: Moving file C:\Users\ahodges\AppData\Local\slack\app-1.2.7\lib\net45\System.Reactive.Linq.dll to C:\Users\ahodges\AppData\Local\slack\app-1.2.7\System.Reactive.Linq.dll
2015-12-10 14:53:10> ApplyReleasesImpl: Moving file C:\Users\ahodges\AppData\Local\slack\app-1.2.7\lib\net45\System.Reactive.PlatformServices.dll to C:\Users\ahodges\AppData\Local\slack\app-1.2.7\System.Reactive.PlatformServices.dll
2015-12-10 14:53:11> ApplyReleasesImpl: Moving file C:\Users\ahodges\AppData\Local\slack\app-1.2.7\lib\net45\vccorlib120.dll to C:\Users\ahodges\AppData\Local\slack\app-1.2.7\vccorlib120.dll
2015-12-10 14:53:11> ApplyReleasesImpl: Moving file C:\Users\ahodges\AppData\Local\slack\app-1.2.7\lib\net45\System.Reactive.Interfaces.dll to C:\Users\ahodges\AppData\Local\slack\app-1.2.7\System.Reactive.Interfaces.dll
2015-12-10 14:53:11> ApplyReleasesImpl: Moving file C:\Users\ahodges\AppData\Local\slack\app-1.2.7\lib\net45\System.Reactive.Windows.Threading.dll to C:\Users\ahodges\AppData\Local\slack\app-1.2.7\System.Reactive.Windows.Threading.dll
2015-12-10 14:53:11> ApplyReleasesImpl: Moving file C:\Users\ahodges\AppData\Local\slack\app-1.2.7\lib\net45\xinput1_3.dll to C:\Users\ahodges\AppData\Local\slack\app-1.2.7\xinput1_3.dll
2015-12-10 14:53:11> ApplyReleasesImpl: Moving file C:\Users\ahodges\AppData\Local\slack\app-1.2.7\lib\net45\ui_resources_200_percent.pak to C:\Users\ahodges\AppData\Local\slack\app-1.2.7\ui_resources_200_percent.pak
2015-12-10 14:53:11> ApplyReleasesImpl: Moving file C:\Users\ahodges\AppData\Local\slack\app-1.2.7\lib\net45\SlackNotifier.dll to C:\Users\ahodges\AppData\Local\slack\app-1.2.7\SlackNotifier.dll
2015-12-10 14:53:12> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\ahodges\AppData\Local\slack\app-1.2.7\slack.exe]
2015-12-10 14:53:15> ApplyReleasesImpl: Starting fixPinnedExecutables
2015-12-10 14:53:15> ApplyReleasesImpl: fixPinnedExecutables: oldAppDirectories is empty, this is pointless
2015-12-10 14:53:15> ApplyReleasesImpl: Fixing up tray icons
2015-12-10 14:53:15> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__f5(RegistryView view)
2015-12-10 14:53:15> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__f5(RegistryView view)
2015-12-10 14:53:15> ApplyReleasesImpl: cleanDeadVersions: for version 1.2.7
2015-12-10 14:53:15> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.2.7
2016-03-08 10:30:58> Program: Starting Squirrel Updater: --install .
2016-03-08 10:30:58> Program: Starting install, writing to C:\Users\ahodges\AppData\Local\SquirrelTemp
2016-03-08 10:30:58> Program: About to install to: C:\Users\ahodges\AppData\Local\GPMDP_3
2016-03-08 10:30:58> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\ahodges\AppData\Local\GPMDP_3\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3f.MoveNext()
2016-03-08 10:30:58> CheckForUpdateImpl: Reading RELEASES file from C:\Users\ahodges\AppData\Local\SquirrelTemp
2016-03-08 10:30:58> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2016-03-08 10:30:58> ApplyReleasesImpl: Writing files to app directory: C:\Users\ahodges\AppData\Local\GPMDP_3\app-3.0.0
2016-03-08 10:31:04> IEnableLogger: Failed to install package to app dir: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Access to the path 'resources' is denied.
   at System.IO.DirectoryInfo.MoveTo(String destDirName)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassb4.<>c__DisplayClassb9.<>c__DisplayClassbb.<installPackageToAppDir>b__b2(DirectoryInfo subdir)
   at Squirrel.Utility.<>c__DisplayClass18`1.<>c__DisplayClass1a.<ForEachAsync>b__17()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassb4.<>c__DisplayClassb9.<installPackageToAppDir>b__b1(DirectoryInfo ld)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassb4.<<installPackageToAppDir>b__ad>d__bd.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__50`1.MoveNext()
---> (Inner Exception #0) System.IO.IOException: Access to the path 'resources' is denied.
   at System.IO.DirectoryInfo.MoveTo(String destDirName)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassb4.<>c__DisplayClassb9.<>c__DisplayClassbb.<installPackageToAppDir>b__b2(DirectoryInfo subdir)
   at Squirrel.Utility.<>c__DisplayClass18`1.<>c__DisplayClass1a.<ForEachAsync>b__17()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()<---

2016-03-08 10:31:04> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Access to the path 'resources' is denied.
   at System.IO.DirectoryInfo.MoveTo(String destDirName)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassb4.<>c__DisplayClassb9.<>c__DisplayClassbb.<installPackageToAppDir>b__b2(DirectoryInfo subdir)
   at Squirrel.Utility.<>c__DisplayClass18`1.<>c__DisplayClass1a.<ForEachAsync>b__17()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassb4.<>c__DisplayClassb9.<installPackageToAppDir>b__b1(DirectoryInfo ld)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassb4.<<installPackageToAppDir>b__ad>d__bd.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__50`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__7a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__38.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Access to the path 'resources' is denied.
   at System.IO.DirectoryInfo.MoveTo(String destDirName)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassb4.<>c__DisplayClassb9.<>c__DisplayClassbb.<installPackageToAppDir>b__b2(DirectoryInfo subdir)
   at Squirrel.Utility.<>c__DisplayClass18`1.<>c__DisplayClass1a.<ForEachAsync>b__17()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassb4.<>c__DisplayClassb9.<installPackageToAppDir>b__b1(DirectoryInfo ld)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassb4.<<installPackageToAppDir>b__ad>d__bd.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__50`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__7a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__38.MoveNext()
---> (Inner Exception #0) System.IO.IOException: Access to the path 'resources' is denied.
   at System.IO.DirectoryInfo.MoveTo(String destDirName)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassb4.<>c__DisplayClassb9.<>c__DisplayClassbb.<installPackageToAppDir>b__b2(DirectoryInfo subdir)
   at Squirrel.Utility.<>c__DisplayClass18`1.<>c__DisplayClass1a.<ForEachAsync>b__17()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()<---
<---


```

**Comment by ajhodges** [comment]
Forgot to add that this is reproducible and I cannot update to 3.0.0 due to this error.

**Comment by MarshallOfSound** [comment]
It sounds like your permissions setup on your PC is a bit strange, we shouldn't be getting access denied on your APPDATA directory.  Can you try running the installer as admin?

**Comment by ajhodges** [comment]
It's possible, I am on my work laptop (who knows what corporate IT has done to this thing :unamused:). Running the player as admin and clicking update worked. But I can't say I've ever had to run any other installers with admin privileges before so I'm not sure what's going on here. Either way, doesn't sound like a high priority bug. Thanks!

**Comment by MarshallOfSound** [comment]
Thanks :+1:
