### ISSUE TITLE
Uncaught Exception: ENOENT: no such file or directory, open '/home/davor/GPMDP_STORE/.settings.json'

### ISSUE THREAD

**Issue by davorb** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#379]
This happened after I resized the window.

An uncaught exception was reported.  
#### Info:
**OS:** linux
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Tue Mar 08 2016 17:33:55 GMT 0100 (CET)

#### Error:
*ENOENT: no such file or directory, open '/home/davor/GPMDP_STORE/.settings.json'*
```js
Error: ENOENT: no such file or directory, open '/home/davor/GPMDP_STORE/.settings.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:159:20)
    at Object.fs.writeFileSync (fs.js:1234:33)
    at Settings._save (/usr/share/google-play-music-desktop-player/resources/app/build/main/utils/Settings.js:82:22)
    at Settings.set (/usr/share/google-play-music-desktop-player/resources/app/build/main/utils/Settings.js:67:14)
    at BrowserWindow._save (/usr/share/google-play-music-desktop-player/resources/app/build/main/features/core/persistAppState.js:17:14)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:169:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
Closed?  Your mistake or what?

**Comment by davorb** [comment]
Yes, this happened because I saw a folder called ```GPMDP_STORE``` in my home folder. I didn't realize what it was, so I removed it. Following that, I got that error after I resized the window.

I opened up #380 instead.

**Comment by MarshallOfSound** [comment]
Ah, the old "delete the unknown folder and watch the world burn" ploy. :+1: 

I do that all the time aswell, we should have a PR merged soon to move the linux config
