### ISSUE TITLE
Uncaught Exception: Command failed: 4294967295

### ISSUE THREAD

**Issue by roryhewitt** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#384]
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.0
**Time:** Tue Mar 08 2016 10:47:50 GMT-0800 (Pacific Standard Time)

#### Error:
*Command failed: 4294967295*
```js
Error: Command failed: 4294967295
System.AggregateException: One or more errors occurred. ---> System.Exception: Couldn't acquire lock, is another instance running
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
   at Squirrel.UpdateManager.<acquireUpdateLock>b__1e()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<Download>d__5d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at Syst
...Some of the stack is missing
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
Client side anti virus causes this issue, if you want it to stop you might have to add an exception to your AV software (normally Norton causes this when it is set to super strict settings)
