### ISSUE TITLE
Uncaught Exception: Command failed: 4294967295

### ISSUE THREAD

**Issue by Pr0tectedV0id** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#415]
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.0
**Time:** Wed Mar 09 2016 14:31:07 GMT-0600 (Central Standard Time)

#### Error:
*Command failed: 4294967295*
```js
Error: Command failed: 4294967295
System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote name could not be resolved: 'update.googleplaymusicdesktopplayer.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__50`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.FileDownloader.<DownloadUrl>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerS
...Some of the stack is missing
```
This issue was created automatically inside the `uncaughtException` handler

NOTE: This occurred due to ISP connectivity issues, not LAN. Maybe just flag this error type and toast a message saying 'Internet Connectivity has been lost. Please check that you're connected to the internet."?

**Comment by MarshallOfSound** [comment]
Client side network issue

Will not be reported in `3.1.0`

Tbh google handles loss of interenet, this is due to an update server ping which will fail without network.  In `3.1.0` the error will just be absorbed
