### ISSUE TITLE
Uncaught Exception: Command failed: 4294967295

### ISSUE THREAD

**Issue by nathanle1406** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#464]
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.0
**Time:** Thu Mar 10 2016 22:29:03 GMT-0600 (Central Standard Time)

#### Error:
*Command failed: 4294967295*
```js
Error: Command failed: 4294967295
System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__4d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.FileDownloader.<DownloadFile>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwait
...Some of the stack is missing
```
This issue was created automatically inside the `uncaughtException` handler

More info added by me:
I didnt notice any problem, but a thing popped up and told me to submit this to github, so here it is. I dont know what most of it means but looks like a http 500 error happened or something? I had the window in the background, and it was paused for a while, so if something went wrong I didn't notice it.

Also i did a google search and found that i had the same error code as issue #213. but he had a different error, something about domain resolution instead of my error 500.

**Comment by MarshallOfSound** [comment]
If you restart the app you'll get an update that fixes this issue

**Comment by nathanle1406** [comment]
I guess in the future i will check the closed issues first. I just noticed the bunch of copies of this issue . Sorry for the duplicate. Anyway i restarted the app and it updated, so problem solved. Thanks!
