### ISSUE TITLE
Uncaught Exception: Command failed: 4294967295

### ISSUE THREAD

**Issue by jonathanrepko** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#488]
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.0
**Time:** Fri Mar 11 2016 10:19:15 GMT-0500 (Eastern Standard Time)

#### Error:
*Command failed: 4294967295*
```js
Error: Command failed: 4294967295
System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__4d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.FileDownloader.<DownloadFile>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwait
...Some of the stack is missing
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
Please restart the app and accept the update.

The update will fix this issue

**Comment by jonathanrepko** [comment]
I did and there was no update offered.

**Comment by MarshallOfSound** [comment]
@jonathanrepko Which version of windows are you running?  Is it a work PC?  Do you have admin right?

**Comment by jonathanrepko** [comment]
Win 10 pro 64 bit. I do have admin creds.

**Comment by MarshallOfSound** [comment]
@jonathanrepko Are you running your network through any proxies/VPN's or other networking tool

**Comment by jonathanrepko** [comment]
no proxies or vpns for the instance where that occurred.
