### ISSUE TITLE
Uncaught Exception: Attempting to call a function in a renderer window that has been closed or released. Function provid

### ISSUE THREAD

**Issue by slimeygecko** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#501]
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.1
**Time:** Fri Mar 11 2016 12:04:26 GMT-0600 (Central Standard Time)

#### Error:
*Attempting to call a function in a renderer window that has been closed or released. Function provid*
```js
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> (C:\Users\mike.woodward\AppData\Local\GPMDP_3\app-3.0.1\resources\app\build\inject\GPMInject\interface\mouseButtonNavigation.js:8:8.
    at BrowserWindow.callIntoRenderer (C:\Users\mike.woodward\AppData\Local\GPMDP_3\app-3.0.1\resources\atom.asar\browser\lib\rpc-server.js:201:19)
    at emitTwo (events.js:92:20)
    at BrowserWindow.emit (events.js:172:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by ryanrapini** [comment]
dupe of #499
