### ISSUE TITLE
Uncaught Exception: Attempting to call a function in a renderer window that has been closed or released. Function provid

### ISSUE THREAD

**Issue by xdpirate** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#529]
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.1
**Time:** Sat Mar 12 2016 19:42:31 GMT 0100 (W. Europe Standard Time)

#### Error:
*Attempting to call a function in a renderer window that has been closed or released. Function provid*
```js
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> (C:\Users\Lars\AppData\Local\GPMDP_3\app-3.0.1\resources\app\build\inject\GPMInject\interface\mouseButtonNavigation.js:8:8.
    at BrowserWindow.callIntoRenderer (C:\Users\Lars\AppData\Local\GPMDP_3\app-3.0.1\resources\atom.asar\browser\lib\rpc-server.js:201:19)
    at emitTwo (events.js:92:20)
    at BrowserWindow.emit (events.js:172:7)
    at EventEmitter.<anonymous> (C:\Users\Lars\AppData\Local\GPMDP_3\app-3.0.1\resources\app\build\main\features\core\controlBar.js:12:45)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.<anonymous> (C:\Users\Lars\AppData\Local\GPMDP_3\app-3.0.1\resources\atom.asar\browser\api\lib\web-contents.js:134:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by xdpirate** [comment]
Duplicate of #528
