### ISSUE TITLE
After reopening the window when it was minimized to taskbar.

### ISSUE THREAD

**Issue by jasonwolf493** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#553]
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.1
**Time:** Sun Mar 13 2016 18:26:07 GMT-0400 (Eastern Daylight Time)

#### Error:
*Attempting to call a function in a renderer window that has been closed or released. Function provid*
```js
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> (C:\Users\Jason\AppData\Local\GPMDP_3\app-3.0.1\resources\app\build\inject\GPMInject\interface\mouseButtonNavigation.js:8:8.
    at BrowserWindow.callIntoRenderer (C:\Users\Jason\AppData\Local\GPMDP_3\app-3.0.1\resources\atom.asar\browser\lib\rpc-server.js:201:19)
    at emitTwo (events.js:92:20)
    at BrowserWindow.emit (events.js:172:7)
    at EventEmitter.<anonymous> (C:\Users\Jason\AppData\Local\GPMDP_3\app-3.0.1\resources\app\build\main\features\core\controlBar.js:4:43)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.<anonymous> (C:\Users\Jason\AppData\Local\GPMDP_3\app-3.0.1\resources\atom.asar\browser\api\lib\web-contents.js:134:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
Is this issue easy to replicate, I.e. Can you make the error popup whenever you want and if so what are the exact steps you take to make to popup

**Comment by MarshallOfSound** [comment]
Also please don't change the title of an automatic issue report, it screws up my automatic handling of the issues

**Comment by jasonwolf493** [comment]
Sorry about the title I was unaware of that. But I cannot replicate it. Maybe it was only something that would happen on the first launch?

**Comment by MarshallOfSound** [comment]
I've seen this issue before, but on different lines of code.  I don't see how the issue can be appearing here unless something strange is going on.  If you can make it do it again, it might help me debug

**Comment by MarshallOfSound** [comment]
I can't for the life of me replicate this, I'm going to close as a strange glitch in a garbage collecter somewhere (best theory I have)
