### ISSUE TITLE
Uncaught Exception: ENFILE: file table overflow, open '/Users/thomashourlier/Library/Application Support/Google Play Mus

### ISSUE THREAD

**Issue by hourliert** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#732]
An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.0.1
**Time:** Tue Mar 22 2016 16:49:51 GMT-0700 (PDT)

#### Error:
*ENFILE: file table overflow, open '/Users/thomashourlier/Library/Application Support/Google Play Mus*
```js
Error: ENFILE: file table overflow, open '/Users/thomashourlier/Library/Application Support/Google Play Music Desktop Player/json_store/playback.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:159:20)
    at Object.fs.writeFileSync (fs.js:1234:33)
    at PlaybackAPI._save (/Applications/Google Play Music Desktop Player.app/Contents/Resources/app/build/main/utils/PlaybackAPI.js:74:22)
    at PlaybackAPI.setTime (/Applications/Google Play Music Desktop Player.app/Contents/Resources/app/build/main/utils/PlaybackAPI.js:114:12)
    at EventEmitter.<anonymous> (/Applications/Google Play Music Desktop Player.app/Contents/Resources/app/build/main/utils/PlaybackAPI.js:48:15)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.<anonymous> (/Applications/Google Play Music Desktop Player.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:134:25)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
From the quick look I just did it appears as though this issue is due to too many files being open on the computer in general so this is caused by another app but we got an error as well :+1:
