### ISSUE TITLE
Uncaught Exceptions when clicking the window borders

### ISSUE THREAD

**Issue by maxlefou** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#739]
I get this random error everytime i give back the focus to the window. And the only way to get rid of it is to click on the link to report it. Though, it doesn't prevent the program to work perfectly.
I noticed it only happens when i click on the borders of the window. Clicking its content doesn't do it.
It also doesn't happen when i use the system window borders. Only with the program builtin borders.

Am I the only one with this? Windows 7 SP1 x64

An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.1
**Time:** Wed Mar 23 2016 12:20:49 GMT 0100 (Paris, Madrid)

#### Error:
*Attempting to call a function in a renderer window that has been closed or released. Function provid*
```js
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> (C:\Users\Max le Fou\AppData\Local\GPMDP_3\app-3.0.1\resources\app\build\inject\GPMInject\interface\mouseButtonNavigation.js:8:8.
    at BrowserWindow.callIntoRenderer (C:\Users\Max le Fou\AppData\Local\GPMDP_3\app-3.0.1\resources\atom.asar\browser\lib\rpc-server.js:201:19)
    at emitTwo (events.js:92:20)
    at BrowserWindow.emit (events.js:172:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by maxlefou** [comment]
**EDIT:** Duplicate of #738. Closing it.
