### ISSUE TITLE
Uncaught Exception: Module version mismatch. Expected 47, got 46.

### ISSUE THREAD

**Issue by MCManuelLP** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#754]
An uncaught exception was reported.  
#### Info:
**OS:** linux
**Arch:** x64
**GPMDP Version:** 3.0.1
**Time:** Thu Mar 24 2016 00:50:37 GMT 0100 (CET)

#### Error:
*Module version mismatch. Expected 47, got 46.*
```js
Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:157:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:157:20)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/manuel/Applications/gpmdp-git/dist/Google Play Music Desktop Player-linux-x64/resources/app/node_modules/dbus/lib/dbus.js:3:13)
    at Module._compile (module.js:425:26)
```
This issue was created automatically inside the `uncaughtException` handler

This has been popping up rather frequently since my last build... 
My current build is more or less up to master (67275e2).
I guess it is probably related to my node install but I don't know how I'm supposed to update 'Module'
This error really doesn't do much, the music skips a track and this message pops up.

**Comment by MarshallOfSound** [comment]
Until I fix the build steps.  Running off master on linux requires that you run `electron-rebuild`
