### ISSUE TITLE
Uncaught Exception: UNKNOWN: unknown error, open 'C:\Users\Username\AppData\Roaming\Google Play Music Desktop Player\json_st

### ISSUE THREAD

**Issue by xdpirate** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#858]
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.1.0
**Time:** Thu Mar 31 2016 13:26:37 GMT 0200 (W. Europe Daylight Time)

#### Error:
*UNKNOWN: unknown error, open 'C:\Users\Username\AppData\Roaming\Google Play Music Desktop Player\json_st*
```js
Error: UNKNOWN: unknown error, open 'C:\Users\Username\AppData\Roaming\Google Play Music Desktop Player\json_store\playback.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:157:20)
    at Object.fs.writeFileSync (fs.js:1234:33)
    at PlaybackAPI._save (C:\Users\Username\AppData\Local\GPMDP_3\app-3.1.0\resources\app\build\main\utils\PlaybackAPI.js:92:22)
    at PlaybackAPI.setTime (C:\Users\Username\AppData\Local\GPMDP_3\app-3.1.0\resources\app\build\main\utils\PlaybackAPI.js:147:12)
    at EventEmitter.<anonymous> (C:\Users\Username\AppData\Local\GPMDP_3\app-3.1.0\resources\app\build\main\utils\PlaybackAPI.js:56:15)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.<anonymous> (C:\Users\Username\AppData\Local\GPMDP_3\app-3.1.0\resources\atom.asar\browser\api\web-contents.js:134:25)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
Did you run the installer as Admin?

**Comment by xdpirate** [comment]
This is after installation,occured randomly while listening. UAC is disabled on the machine, so everything is automatically elevated.

**Comment by MarshallOfSound** [comment]
Hmmmm, to be honest an `UNKNOWN: unknown error` is distinctly not helpful :laughing: 

There was another issue like this somewhere which I believe I fixed with some `chmod` magic so I'm going to close this as a fixed duplicate :+1:
