### ISSUE TITLE
Uncaught Exception: ENOENT: no such file or directory, open '/home/chris/GPMDP_STORE/playback.json'

### ISSUE THREAD

**Issue by chrisjackson4256** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#895]
An uncaught exception was reported.  
#### Info:
**OS:** linux
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Mon Apr 04 2016 23:11:46 GMT-0500 (CDT)

#### Error:
*ENOENT: no such file or directory, open '/home/chris/GPMDP_STORE/playback.json'*
```js
Error: ENOENT: no such file or directory, open '/home/chris/GPMDP_STORE/playback.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:159:20)
    at Object.fs.writeFileSync (fs.js:1234:33)
    at PlaybackAPI._save (/usr/share/google-play-music-desktop-player/resources/app/build/main/utils/PlaybackAPI.js:83:20)
    at PlaybackAPI.setTime (/usr/share/google-play-music-desktop-player/resources/app/build/main/utils/PlaybackAPI.js:122:12)
    at EventEmitter.<anonymous> (/usr/share/google-play-music-desktop-player/resources/app/build/main/utils/PlaybackAPI.js:58:15)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.<anonymous> (/usr/share/google-play-music-desktop-player/resources/atom.asar/browser/api/lib/web-contents.js:120:25)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by jostrander** [comment]
You are using a way outdated version, could you please download and update to 3.1.0?

**Comment by chrisjackson4256** [comment]
thanks... didn't realize my version was so out of date.  it had been working great until tonight.

**Comment by jostrander** [comment]
Mostly feature updates, but also a lot of bug fixes, especially for linux ;)

**Comment by chrisjackson4256** [comment]
it's a great little app... i love it.  thanks again.
