### ISSUE TITLE
Uncaught Exception: UNKNOWN: unknown error, open 'C:\Users\kazemifa\AppData\Roaming\Google Play Music Desktop Player\jso

### ISSUE THREAD

**Issue by fkazemi** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#943]
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.1.0
**Time:** Fri Apr 15 2016 12:52:16 GMT-0400 (Eastern Daylight Time)

#### Error:
*UNKNOWN: unknown error, open 'C:\Users\x\AppData\Roaming\Google Play Music Desktop Player\jso*
```js
Error: UNKNOWN: unknown error, open 'C:\Users\x\AppData\Roaming\Google Play Music Desktop Player\json_store\playback.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:157:20)
    at Object.fs.writeFileSync (fs.js:1234:33)
    at PlaybackAPI._save (C:\Users\x\AppData\Local\GPMDP_3\app-3.1.0\resources\app\build\main\utils\PlaybackAPI.js:92:22)
    at PlaybackAPI.setTime (C:\Users\x\AppData\Local\GPMDP_3\app-3.1.0\resources\app\build\main\utils\PlaybackAPI.js:147:12)
    at EventEmitter.<anonymous> (C:\Users\x\AppData\Local\GPMDP_3\app-3.1.0\resources\app\build\main\utils\PlaybackAPI.js:56:15)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.<anonymous> (C:\Users\x\AppData\Local\GPMDP_3\app-3.1.0\resources\atom.asar\browser\api\web-contents.js:134:25)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
The unicorn will close this soon as it is a duplicate.

But some quick things to help you fix it.  
1. Did you install by "Running as Admin"?  If so, uninstall, then reinstall without running as admin.
2. Are you running this on a work PC with certain permission restrictions?

**Comment by MarshallOfSound** [comment]
Bad @GPMDP-Magical-Unicorn ....
