### ISSUE TITLE
Uncaught Exception: ENOENT: no such file or directory, open '/home/colin/GPMDP_STORE/.settings.json'

### ISSUE THREAD

**Issue by colinclement** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#945]
An uncaught exception was reported.  
#### Info:
**OS:** linux
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Fri Apr 15 2016 14:12:00 GMT-0400 (EDT)

#### Error:
*ENOENT: no such file or directory, open '/home/colin/GPMDP_STORE/.settings.json'*
```js
Error: ENOENT: no such file or directory, open '/home/colin/GPMDP_STORE/.settings.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:159:20)
    at Object.fs.writeFileSync (fs.js:1234:33)
    at Settings._save (/usr/share/google-play-music-desktop-player/resources/app/build/main/utils/Settings.js:82:22)
    at Settings.set (/usr/share/google-play-music-desktop-player/resources/app/build/main/utils/Settings.js:67:14)
    at BrowserWindow._save (/usr/share/google-play-music-desktop-player/resources/app/build/main/features/core/persistAppState.js:17:14)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:169:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by jostrander** [comment]
You are using an outdated version of GPMDP. Please manually update by downloading the latest package from http://gpmdp.xyz.
