### ISSUE TITLE
Uncaught Exception: Cannot find module 'dbus'

### ISSUE THREAD

**Issue by NessDan** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#993]
An uncaught exception was reported.  
#### Info:
**OS:** linux
**Arch:** x64
**GPMDP Version:** 3.2.1
**Time:** Thu Apr 28 2016 17:24:13 GMT-0400 (EDT)

#### Error:
*Cannot find module 'dbus'*
```js
Error: Cannot find module 'dbus'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/share/google-play-music-desktop-player/resources/app/build/main/features/linux/mediaKeysDBus.js:3:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by jostrander** [comment]
What version of linux?

**Comment by NessDan** [comment]
Ubuntu 15.10, up to date and everything.

**Comment by MarshallOfSound** [comment]
@NessDan Are you running from master or from a release version?

**Comment by NessDan** [comment]
Master, I cloned the repo from Github yesterday, ran the build steps, and
installed it.

Is the dbus package a requirement for the app or is this another issue?

**Comment by MarshallOfSound** [comment]
Sounds like your `npm install` failed and missed a few packages.  In this case the dbus package.

Delete your `node_modules` folder and rerun `npm install`, then just check there is a `dbus` folder inside the `node_modules` folder

**Comment by NessDan** [comment]
I think you're on to something.

I got these errors:

```
npm WARN optional Skipping failed optional dependency
//ll-keyboard-hook-win:
npm WARN notsup Not compatible with your operating system or architecture:
ll-keyboard-hook-win@3.0.0
npm WARN chai-fs@0.1.0 requires a peer of chai@>= 1.6.1 < 2 but none was
installed.
```

Then running `npm run make:deb`, I got this error:

```
> mouse-forward-back@1.0.1 install
/home/dkaspo/code/google-play-music-unofficial/node_modules/mouse-forward-back
> node-gyp rebuild

make: Entering directory
'/home/dkaspo/code/google-play-music-unofficial/node_modules/mouse-forward-back/build'
  CXX(target) Release/obj.target/mouse-forward-back/mouse-forward-back.o
mouse-forward-back.target.mk:88: recipe for target
'Release/obj.target/mouse-forward-back/mouse-forward-back.o' failed
make: Leaving directory
'/home/dkaspo/code/google-play-music-unofficial/node_modules/mouse-forward-back/build'


In file included from /usr/include/errno.h:28:0,
                 from
/home/dkaspo/code/google-play-music-unofficial/node_modules/electron-rebuild/lib/headers/.node-gyp/0.37.7/deps/uv/include/uv-errno.h:25,
                 from
/home/dkaspo/code/google-play-music-unofficial/node_modules/electron-rebuild/lib/headers/.node-gyp/0.37.7/deps/uv/include/uv.h:48,
                 from ../../nan/nan.h:46,
                 from ../mouse-forward-back.cc:1:
/usr/include/features.h:364:25: fatal error: sys/cdefs.h: No such file or
directory
compilation terminated.
make: *** [Release/obj.target/mouse-forward-back/mouse-forward-back.o]
Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit
(/home/dkaspo/code/google-play-music-unofficial/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:204:12)
gyp ERR! System Linux 4.2.0-35-generic
gyp ERR! command "/usr/bin/nodejs"
"/home/dkaspo/code/google-play-music-unofficial/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"rebuild"
gyp ERR! cwd
/home/dkaspo/code/google-play-music-unofficial/node_modules/mouse-forward-back
gyp ERR! node -v v5.11.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok

npm ERR! Linux 4.2.0-35-generic
npm ERR! argv "/usr/bin/nodejs"
"/home/dkaspo/code/google-play-music-unofficial/node_modules/npm/bin/npm-cli.js"
"rebuild" "--runtime=electron" "--target=0.37.7" "--arch=ia32"
npm ERR! node v5.11.0
npm ERR! npm  v3.8.8
npm ERR! code ELIFECYCLE
npm ERR! mouse-forward-back@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mouse-forward-back@1.0.1 install script 'node-gyp
rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the
mouse-forward-back package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project
with:
npm ERR!     npm bugs mouse-forward-back
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mouse-forward-back
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/home/dkaspo/code/google-play-music-unofficial/node_modules/npm-debug.log


Process exited with code: 1
Error: Process exited with code: 1
    at ChildProcess.<anonymous>
(/home/dkaspo/code/google-play-music-unofficial/node_modules/electron-rebuild/lib/spawn.js:55:26)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

Rebuild complete
```

**Comment by jostrander** [comment]
Did you install all the dependencies from circle.yml?

**Comment by NessDan** [comment]
@jostrander No clue, I just followed the README instructions.

**Comment by jostrander** [comment]
There's currently an issue with building for a single architecture on Linux
so you have to install all the deps from circle.yml in order to build.
You'll see the deps listed as apt-get commands with you can run yourself.

Unfortunately the packages will still build without some of the deps from
circle because they are optional dependencies for so they won't cause build
failures on windows/OS X.

**Comment by jostrander** [comment]
Also you might be able to get away with only installing the 64 bit versions
of the packages needed from circle.yml, but you'll still get errors from
the ia32 build when packaging.

**Comment by NessDan** [comment]
Thanks @jostrander , I installed all those dependencies manually, rebuilt everything, still got the errors I listed above _but_ the GP app isn't showing those errors anymore :smiley:

Thanks everyone!

**Comment by jostrander** [comment]
:+1: No problem
